steps/carthage/1.0.0/step.yml

Step for setting up a project with [`Carthage`](https://github.com/Carthage/Carthage) dependency manager.

carthage 1.0.0

---

steps/carthage/1.0.1/step.yml

carthage 1.0.1

---

steps/carthage/1.0.2/step.yml

carthage 1.0.2

---

steps/carthage/1.0.3/step.yml

Removed workaround for https://github.com/Homebrew/homebrew/commit/c4e4043fb856741b117bed96d5cb37206713937b

carthage 1.0.3

---

steps/xcode-test-mac/1.0.0/step.yml

xcode-test-mac 1.0.0

---

steps/xcode-test-mac/1.0.1/step.yml

Fixes incorrectly set default value for input param

xcode-test-mac 1.0.1

---

steps/xcode-test-mac/1.0.2/step.yml

With `bitrise.yml` and updated readme. Fix of a syntax error.

xcode-test-mac 1.0.2

---

steps/appaloosa/1.1.0/step.yml

Rename routes and Fix variable name

appaloosa 1.1.0

---

steps/carthage/1.0.5/step.yml

carthage 1.0.5

---

steps/xcode-test-mac/1.0.3/step.yml

Update description to make it more clear this step is for Mac builds

xcode-test-mac 1.0.3

---

steps/xcode-archive-mac/0.1.0/step.yml

@viktorbenei @godrei can you please take look if it seems right/if you miss something? I have some issues with that rvm workaround, but the problem might be with my setup. Still, I might need some clarification on that part to be able to test it.

Xcode archive step mac

---

steps/lifx/1.0.0/step.yml

As already described [here](https://github.com/bitrise-io/bitrise-steplib/pull/247). Id of step is now lowercase.

lifx 1.0.0

---

steps/carthage/1.0.6/step.yml

Adds `carthage_options` general input field & bitrise.yml for CLI usage

carthage 1.0.6

---

steps/xcode-archive-mac/1.1.2/step.yml

Fixes improper file export format usage

xcode-archive-mac 1.1.2

---

steps/carthage/1.0.7/step.yml

Adds `tvOs` and `all` to platform options

carthage 1.0.7

---

steps/lifx/1.1.0/step.yml

New version with much improved descriptions and logic.

lifx 1.1.0

---

steps/carthage/1.0.8/step.yml

carthage 1.0.8

---

steps/carthage/2.0.0/step.yml

carthage 2.0.0

---

steps/codecov-android/1.0.0/step.yml

This step add codecov support for android projects.

codecov-android 1.0.0

---

steps/cordova-android/0.9.1/step.yml

Fixed bug with `npm` tool check, before running `cordova` command.

cordova-android 0.9.1

---

steps/xcode-test-mac/1.0.4/step.yml

Fix issue with building workspaces

xcode-test-mac 1.0.4

---

steps/xcode-archive-mac/1.1.3/step.yml

Fixes signing with no identity

xcode-archive-mac 1.1.3

---

steps/xcode-archive-mac/1.1.4/step.yml

xcode-archive-mac 1.1.4

---

steps/installrapp-deploy/1.0.1/step.yml

This adds support for InstallrApp.com as requested in bitrise-io/bitrise-contrib#11
Should fix the issues from the original PR #393

installrapp-deploy 1.0.1

---

steps/set-android-manifest-package-name/0.9.0/step.yml

The step allows to change android manifest package name

set-android-manifest-package-name 0.9.0

---

steps/xcode-project-info/1.0.1/step.yml

Ok, here's another take on #430 and #431. :)

Add new step: xcode-project-info 1.0.1

---

steps/xcode-project-info/1.0.2/step.yml

Fixed issue with project directory path containing white space.

xcode-project-info 1.0.2

---

steps/carthage/2.0.2/step.yml

carthage 2.0.2

---

steps/applivery-android/0.2.0/step.yml

Improved version including:
- Some Bitrise exposed variables for a deeper integration between Applivery & Bitrise
- Minor bug fixing

applivery-android 0.2.0

---

steps/applivery-ios/0.2.0/step.yml

Improved version including:
- Some Bitrise exposed variables for a deeper integration between Applivery & Bitrise
- Minor bug fixing

applivery-ios 0.2.0

---

steps/set-ios-bundle-identifier/1.0.1/step.yml

Step - Set iOS Bundle Identifier v1.0.1
Please review and accept the PR, thanks!

Step - Set iOS Bundle Identifier v1.0.1

---

steps/set-ios-bundle-identifier/1.0.2/step.yml

Fixed info.plist path in quotes to allow spaced file path values, thanks!

set-ios-bundle-identifier 1.0.2

---

steps/web-translate-it/1.0.1/step.yml

Re-Publish of bitrise-io/bitrise-steplib#452.

web-translate-it 1.0.1

---

steps/carthage/2.1.0/step.yml

Caching logic for `bootstrap` command

carthage 2.1.0

---

steps/cocoaseeds-install/1.0.0/step.yml

[CocoaSeeds](https://github.com/devxoul/CocoaSeeds)

cocoaseeds-install step 1.0.0

---

steps/web-translate-it/1.0.2/step.yml

This fixes an issue that the current directory was not taken as a working directory, if no working directory was given. My bad 🙈.

web-translate-it 1.0.2

---

steps/carthage/2.1.1/step.yml

carthage 2.1.1

---

steps/set-ios-version/1.1.0/step.yml

Fixes, Append Version, Short Version increment

step-ios-version 1.1.0

---

steps/set-ios-version/1.1.1/step.yml

Fix append version config bug

---

steps/version-pre-release-info/1.0.1/step.yml

Fix the name of the `version_prefix` input parameter

version-pre-release-info 1.0.1

---

steps/xamarin-builder/1.3.4/step.yml

xamarin-builder 1.3.4

---

steps/file-downloader/0.9.1/step.yml

file-downloader 0.9.1

---

steps/cocoapods-install/1.5.0/step.yml

cocoapods-install 1.5.0

---

steps/cocoapods-install/1.5.1/step.yml

cocoapods-install 1.5.1

---

steps/cocoapods-install/1.5.2/step.yml

cocoapods-install 1.5.2

---

steps/xcode-archive/1.8.2/step.yml

xcode-archive 1.8.2

---

steps/sign-apk/0.9.8/step.yml

sign-apk 0.9.8

---

steps/project-scanner/0.9.6/step.yml

project-scanner 0.9.6

---

steps/project-scanner/0.9.7/step.yml

project-scanner 0.9.7

---

steps/version-pre-release-info/1.0.2/step.yml

version-pre-release-info 1.0.2

---

steps/codecov/1.1.0/step.yml

codecov 1.1.0

---

steps/xamarin-test-cloud-for-android/1.2.1/step.yml

xamarin-test-cloud-for-android 1.2.1

---

steps/carthage/2.1.2/step.yml

carthage 2.1.2

---

steps/certificate-and-profile-installer/1.6.0/step.yml

certificate-and-profile-installer 1.6.0

---

steps/xcode-test-mac/1.0.5/step.yml

xcode-test-mac 1.0.5

---

steps/xcode-archive-mac/1.1.6/step.yml

xcode-archive-mac 1.1.6

---

steps/carthage/1.0.0/step.yml
steps/carthage/1.0.1/step.yml
steps/carthage/1.0.2/step.yml
steps/carthage/1.0.3/step.yml
steps/carthage/1.0.4/step.yml
steps/carthage/1.0.5/step.yml
steps/carthage/1.0.6/step.yml
steps/carthage/1.0.7/step.yml
steps/carthage/1.0.8/step.yml
steps/carthage/2.0.0/step.yml
steps/carthage/2.0.1/step.yml
steps/carthage/2.0.2/step.yml
steps/carthage/2.1.0/step.yml
steps/carthage/2.1.1/step.yml
steps/xcode-archive-mac/0.1.0/step.yml
steps/xcode-archive-mac/1.0.0/step.yml
steps/xcode-archive-mac/1.1.0/step.yml
steps/xcode-archive-mac/1.1.1/step.yml
steps/xcode-archive-mac/1.1.2/step.yml
steps/xcode-archive-mac/1.1.3/step.yml
steps/xcode-archive-mac/1.1.4/step.yml
steps/xcode-test-mac/1.0.0/step.yml
steps/xcode-test-mac/1.0.1/step.yml
steps/xcode-test-mac/1.0.2/step.yml
steps/xcode-test-mac/1.0.3/step.yml
steps/xcode-test-mac/1.0.4/step.yml

migrate steps from vasarhelyia to bitrise-steplib

---

steps/codecov/1.1.1/step.yml

codecov 1.1.1

---

steps/xcode-archive-mac/1.2.0/step.yml

xcode-archive-mac 1.2.0

---

steps/sign-apk/1.0.1/step.yml

sign-apk 1.0.1

---

steps/xamarin-builder/1.3.5/step.yml

xamarin-builder 1.3.5

---

steps/xamarin-ios-test/1.0.3/step.yml

xamarin-ios-test 1.0.3

---

steps/codecov/1.1.2/step.yml

codecov 1.1.2

---

bitrise.yml

bitrise.yml update

---

steps/codecov/1.1.3/step.yml

codecov 1.1.3

---

_scripts/deploy/deploy_to_s3.go

deploy to s3 local collection file:// prefix fix

---

steps/project-scanner/0.9.8/step.yml

project-scanner 0.9.8

---

steps/cocoapods-install/1.5.4/step.yml

cocoapods-install 1.5.4

---

steps/xamarin-builder/1.3.6/step.yml

xamarin-builder 1.3.6

---

steps/xamarin-test-cloud-for-ios/1.2.1/step.yml

xamarin-test-cloud-for-ios 1.2.1

---

steps/xcode-archive/1.8.4/step.yml

xcode-archive 1.8.4

---

steps/xcode-archive/1.8.5/step.yml

xcode-archive 1.8.5

---

steps/recreate-user-schemes/0.9.0/step.yml

recreate-user-schemes 0.9.0

---

steps/project-scanner/0.9.9/step.yml

project-scanner 0.9.9

---

steps/git-clone/3.3.0/step.yml

git-clone 3.3.0

---

steps/recreate-user-schemes/0.9.1/step.yml

recreate-user-schemes 0.9.1

---

steps/project-scanner/0.9.10/step.yml

project-scanner 0.9.10

---

steps/script/1.1.2/step.yml

script 1.1.2

---

steps/post-jira-comment-with-build-details/0.1.6/step.yml

- Minor improvement to add a branch pattern

post-jira-comment-with-build-details 0.1.6

---

steps/git-clone/3.3.1/step.yml

git-clone 3.3.1

---

steps/activate-ssh-key/3.1.1/step.yml

activate-ssh-key 3.1.1

---

steps/random-quote/3.0.2/step.yml

random-quote 3.0.2

---

steps/git-clone/3.3.2/step.yml

git-clone 3.3.2

---

steps/set-xcode-build-number/1.0.4/step.yml

set-xcode-build-number 1.0.4

---

steps/post-jira-comment-with-build-details/0.1.8/step.yml

post-jira-comment-with-build-details 0.1.8

---

steps/deploy-to-itunesconnect-deliver/2.6.1/step.yml

deploy-to-itunesconnect-deliver 2.6.1

---

steps/git-clone/3.3.3/step.yml

git-clone 3.3.3

---

steps/resign-ipa/1.0.0/step.yml

resign-ipa 1.0.0

---

steps/carthage/2.2.0/step.yml

carthage 2.2.0

---

steps/project-scanner/0.9.11/step.yml

project-scanner 0.9.11

---

steps/nuget-restore/0.9.3/step.yml

nuget-restore 0.9.3

---

steps/xcode-archive/1.9.0/step.yml

xcode-archive 1.9.0

---

steps/cocoapods-install/1.5.5/step.yml

cocoapods-install 1.5.5

---

steps/xcode-archive-mac/1.3.0/step.yml

xcode-archive-mac 1.3.0

---

steps/xamarin-builder/1.3.7/step.yml

xamarin-builder 1.3.7

---

steps/xamarin-test-cloud-for-calabash-ios/0.9.4/step.yml

xamarin-test-cloud-for-calabash-ios 0.9.4

---

steps/gradle-runner/1.4.0/step.yml

gradle-runner 1.4.0

---

steps/gradle-runner/1.4.1/step.yml

gradle-runner 1.4.1

---

steps/cocoapods-install/1.5.6/step.yml

cocoapods-install 1.5.6

---

steps/react-native-bundle/0.2.0/step.yml

react-native-bundle 0.2.0

---

steps/start-android-emulator/1.1.0/step.yml

start-android-emulator 1.1.0

---

steps/git-clone/3.3.4/step.yml

git-clone 3.3.4

---

steps/resign-ipa/1.1.0/step.yml

resign-ipa 1.1.0

---

steps/xamarin-builder/1.4.0/step.yml

xamarin-builder 1.4.0

---

steps/react-native-bundle/1.0.0/step.yml

react-native-bundle 1.0.0

---

steps/deploy-to-bitrise-io/1.2.5/step.yml

deploy-to-bitrise-io 1.2.5

---

steps/xamarin-test-cloud-for-android/1.2.2/step.yml

xamarin-test-cloud-for-android 1.2.2

---

steps/react-native-bundle/1.0.1/step.yml

react-native-bundle 1.0.1

---

steps/xcode-archive/1.9.1/step.yml

xcode-archive 1.9.1

---

steps/script/1.1.3/step.yml

script 1.1.3

---

steps/xamarin-test-cloud-for-ios/1.2.2/step.yml

xamarin-test-cloud-for-ios 1.2.2

---

steps/xamarin-test-cloud-for-android/1.2.3/step.yml

xamarin-test-cloud-for-android 1.2.3

---

steps/xamarin-ios-test/1.0.4/step.yml

xamarin-ios-test 1.0.4

---

steps/nunit-runner/0.9.3/step.yml

nunit-runner 0.9.3

---

steps/cocoapods-install/1.5.7/step.yml

cocoapods-install 1.5.7

---

steps/project-scanner/0.9.12/step.yml

project-scanner 0.9.12

---

steps/recreate-user-schemes/0.9.4/step.yml

recreate-user-schemes 0.9.4

---

steps/project-scanner/0.9.13/step.yml

project-scanner 0.9.13

---

steps/carthage/2.3.0/step.yml

carthage 2.3.0

---

steps/slack/2.2.0/step.yml

slack 2.2.0

---

steps/slack/2.3.0/step.yml

slack 2.3.0

---

steps/xamarin-builder/1.4.1/step.yml

xamarin-builder 1.4.1

---

steps/gradle-runner/1.5.0/step.yml

gradle-runner 1.5.0

---

steps/certificate-and-profile-installer/1.7.0/step.yml

certificate-and-profile-installer 1.7.0

---

steps/hockeyapp-deploy-android/1.1.0/step.yml

hockeyapp-deploy-android 1.1.0

---

steps/xamarin-user-management/1.0.3/step.yml

xamarin-user-management 1.0.3

---

steps/gradle-runner/1.5.1/step.yml

gradle-runner 1.5.1

---

steps/amazon-s3-uploader/1.0.1/step.yml

Apologies for this, its friday, my brain is a bit fried :)

amazon-s3-uploader 1.0.1

---

steps/project-scanner/0.9.14/step.yml

project-scanner 0.9.14

---

steps/fabric-crashlytics-beta-deploy/2.2.0/step.yml

fabric-crashlytics-beta-deploy 2.2.0

---

steps/xcode-archive/1.9.2/step.yml

xcode-archive 1.9.2

---

steps/deploy-to-itunesconnect-deliver/2.6.2/step.yml

deploy-to-itunesconnect-deliver 2.6.2

---

steps/deploy-to-itunesconnect-shenzhen/2.1.2/step.yml

deploy-to-itunesconnect-shenzhen 2.1.2

---

PULL_REQUEST_TEMPLATE.md

change requested by @viktorbenei, see https://bitrise.slack.com/archives/general/p1474561510001453

Update PR checklist to reference audit-this-step workflow instead of stepman

---

steps/aws-device-farm-file-deploy/0.0.2/step.yml

aws-device-farm-file-deploy 0.0.2

---

steps/xcode-archive/1.10.0/step.yml

xcode-archive 1.10.0

---

steps/aws-device-farm-runner/0.0.2/step.yml

aws-device-farm-runner 0.0.2

---

steps/carthage/2.4.0/step.yml

carthage 2.4.0

---

steps/gradle-runner/1.5.2/step.yml

gradle-runner 1.5.2

---

steps/project-scanner/0.10.0/step.yml

project-scanner 0.10.0

---

steps/sign-apk/1.1.0/step.yml

sign-apk 1.1.0

---

steps/xcode-test/1.17.0/step.yml

xcode-test 1.17.0

---

steps/git-clone/3.4.0/step.yml

git-clone 3.4.0

---

steps/project-scanner/0.10.1/step.yml

project-scanner 0.10.1

---

steps/xcode-archive-mac/1.3.1/step.yml

xcode-archive-mac 1.3.1

---

steps/lifx-notifier/1.0.0/step.yml

lifx-notifier 1.0.0

---

steps/lifx-notifier/1.0.1/step.yml

Contains fixes: 
https://github.com/vgaidarji/steps-lifx-notifier/issues/1
https://github.com/vgaidarji/steps-lifx-notifier/issues/2
https://github.com/vgaidarji/steps-lifx-notifier/issues/3

lifx-notifier 1.0.1

---

steps/xcode-test/1.17.1/step.yml

xcode-test 1.17.1

---

steps/xcode-archive/1.10.1/step.yml

xcode-archive 1.10.1

---

steps/project-scanner/0.11.0/step.yml

project-scanner 0.11.0

---

steps/appaloosa/1.2.0/step.yml

Fix:
+ description was breaking when user put quotes and special characters.
Feature:
+ add support for a new changelog field.

appaloosa 1.2.0

---

steps/sign-apk/1.1.1/step.yml

sign-apk 1.1.1

---

steps/appaloosa/1.2.1/step.yml

Fix issue in .sh file when calling ruby script.

appaloosa 1.2.1

---

steps/post-jira-comment-with-build-details/0.1.9/step.yml

post-jira-comment-with-build-details 0.1.9

---

steps/xamarin-archive/0.9.0/step.yml

xamarin-archive 0.9.0

---

steps/export-xcarchive/0.9.0/step.yml

export-xcarchive 0.9.0

---

steps/export-xcarchive-mac/0.9.0/step.yml

export-xcarchive-mac 0.9.0

---

steps/appaloosa/1.2.3/step.yml

Last time, promise! Fixing the 1.2.2 version.
We have planned on creating tests for this step, coming soon.

appaloosa 1.2.3

---

steps/xamarin-test-cloud-for-android/2.0.0/step.yml

xamarin-test-cloud-for-android 2.0.0

---

steps/xamarin-test-cloud-for-ios/2.0.0/step.yml

xamarin-test-cloud-for-ios 2.0.0

---

steps/nunit-runner/1.0.0/step.yml

nunit-runner 1.0.0

---

steps/apk-info/1.0.4/step.yml

apk-info 1.0.4

---

steps/xamarin-ios-test/2.0.0/step.yml

xamarin-ios-test 2.0.0

---

steps/apk-info/1.1.0/step.yml

Update to 1.1.0, more cleanup, better formating, better getting APK icon.

apk-info 1.1.0

---

steps/nuget-restore/1.0.0/step.yml

nuget-restore 1.0.0

---

steps/gradle-unit-test/1.0.0/step.yml

gradle-unit-test 1.0.0

---

steps/gradle-unit-test/1.0.1/step.yml

gradle-unit-test 1.0.1

---

steps/xcode-test-bundle-builder/0.0.4/step.yml

xcode-test-bundle-builder 0.0.4

---

steps/apk-info/1.1.1/step.yml

apk-info 1.1.1

---

steps/resign-ipa/1.2.0/step.yml

resign-ipa 1.2.0

---

steps/nuget-restore/1.0.1/step.yml

nuget-restore 1.0.1

---

steps/google-play-deploy/1.0.0/step.yml

google-play-deploy 1.0.0

---

steps/certificate-and-profile-installer/1.8.0/step.yml

certificate-and-profile-installer 1.8.0

---

steps/calabash-ios-uitest/1.0.0/step.yml

calabash-ios-uitest 1.0.0

---

steps/xamarin-test-cloud-for-android/2.1.0/step.yml

xamarin-test-cloud-for-android 2.1.0

---

steps/xamarin-test-cloud-for-ios/2.1.0/step.yml

xamarin-test-cloud-for-ios 2.1.0

---

steps/xamarin-archive/1.0.0/step.yml

xamarin-archive 1.0.0

---

steps/xamarin-ios-test/2.1.0/step.yml

xamarin-ios-test 2.1.0

---

steps/nunit-runner/1.1.0/step.yml

nunit-runner 1.1.0

---

steps/calabash-ios-uitest/1.1.0/step.yml

calabash-ios-uitest 1.1.0

---

steps/calabash-android-uitest/1.0.0/step.yml

calabash-android-uitest 1.0.0

---

steps/xcode-archive-mac/1.3.2/step.yml

xcode-archive-mac 1.3.2

---

steps/certificate-and-profile-installer/1.8.1/step.yml

certificate-and-profile-installer 1.8.1

---

steps/fabric-crashlytics-beta-deploy/2.2.1/step.yml

fabric-crashlytics-beta-deploy 2.2.1

---

steps/nunit-runner/1.1.1/step.yml

nunit-runner 1.1.1

---

steps/git-clone/3.4.1/step.yml

git-clone 3.4.1

---

steps/xamarin-archive/1.1.0/step.yml

xamarin-archive 1.1.0

---

steps/project-scanner/0.11.1/step.yml

project-scanner 0.11.1

---

steps/monkop-android/1.0.1/step.yml

monkop-android 1.0.1

---

steps/xamarin-archive/1.1.1/step.yml

xamarin-archive 1.1.1

---

steps/project-scanner/0.11.2/step.yml

project-scanner 0.11.2

---

steps/ipa-info/1.0.0/step.yml

ipa-info 1.0.0

---

steps/ipa-info/assets/icon.svg

ipa-info: Added SVG icon

---

steps/giphy/0.1.1/step.yml

Hi guys,
I'm submitting a new version for the Giphy step, allowing users to have spaces in their gifs suggestions (See https://github.com/Almouro/bitrise-giphy-step/commit/0492814eef11db70ed8c0dc98eeefce2bf751afd).
Thanks!

giphy 0.1.1

---

steps/appaloosa/1.3.0/step.yml

appaloosa 1.3.0

---

steps/xcode-test/1.17.2/step.yml

xcode-test 1.17.2

---

steps/amazon-s3-deploy/3.5.1/step.yml

amazon-s3-deploy 3.5.1

---

steps/carthage/3.0.0/step.yml

carthage 3.0.0

---

steps/xcode-archive/2.0.0/step.yml

xcode-archive 2.0.0

---

steps/xcode-archive/2.0.1/step.yml

xcode-archive 2.0.1

---

steps/xcode-test/1.18.0/step.yml

xcode-test 1.18.0

---

steps/google-play-deploy/1.0.1/step.yml

google-play-deploy 1.0.1

---

steps/google-play-deploy/1.1.0/step.yml

google-play-deploy 1.1.0

---

steps/bower/0.1.2/step.yml

Add 'Bower' Step 

---

steps/gulp/0.1.0/step.yml

Add 'Gulp' step

---

steps/deploy-to-itunesconnect-deliver/2.6.3/step.yml

deploy-to-itunesconnect-deliver 2.6.3

---

steps/xcode-archive/2.0.2/step.yml

xcode-archive 2.0.2

---

steps/export-xcarchive/0.9.1/step.yml

export-xcarchive 0.9.1

---

steps/export-xcarchive-mac/0.9.1/step.yml

export-xcarchive-mac 0.9.1

---

steps/create-android-emulator/1.0.0/step.yml

create-android-emulator 1.0.0

---

steps/xcode-test/1.18.1/step.yml

xcode-test 1.18.1

---

steps/xcode-archive/2.0.3/step.yml

xcode-archive 2.0.3

---

steps/nuget-restore/1.0.2/step.yml

nuget-restore 1.0.2

---

steps/github-status/0.9.0/step.yml

github-status 0.9.0

---

steps/cordova-ios/0.1.0/step.yml

Add cordova for macosx stacks

---

steps/bower/0.1.3/step.yml

bower 0.1.3 (updated step)

---

steps/gulp/0.1.1/step.yml

Gulp 0.1.1 (updated step)

---

steps/git-tag/1.1.0/step.yml

git-tag 1.1.0

---

steps/nuget-restore/1.0.3/step.yml

nuget-restore 1.0.3

---

steps/nunit-runner/1.1.2/step.yml

nunit-runner 1.1.2

---

steps/cocoapods-install/1.5.8/step.yml

cocoapods-install 1.5.8

---

steps/deploy-to-itunesconnect-deliver/2.7.0/step.yml

deploy-to-itunesconnect-deliver 2.7.0

---

steps/xcode-archive/2.0.4/step.yml

xcode-archive 2.0.4

---

steps/aws-device-farm-runner/0.0.3/step.yml

aws-device-farm-runner 0.0.3

---

steps/deploy-to-itunesconnect-deliver/2.7.1/step.yml

deploy-to-itunesconnect-deliver 2.7.1

---

steps/carthage/3.0.1/step.yml

carthage 3.0.1

---

steps/aws-device-farm-runner/0.0.4/step.yml

aws-device-farm-runner 0.0.4

---

steps/project-scanner/0.11.3/step.yml

project-scanner 0.11.3

---

steps/ipa-info/1.0.1/step.yml

ipa-info 1.0.1

---

steps/install-react-native/0.9.1/step.yml

install-react-native 0.9.1

---

steps/react-native-bundle/1.0.2/step.yml

react-native-bundle 1.0.2

---

steps/deploy-to-itunesconnect-deliver/2.7.2/step.yml

deploy-to-itunesconnect-deliver 2.7.2

---

steps/recreate-user-schemes/0.9.5/step.yml

recreate-user-schemes 0.9.5

---

steps/project-scanner/0.11.4/step.yml

project-scanner 0.11.4

---

steps/export-xcarchive/0.9.2/step.yml

export-xcarchive 0.9.2

---

steps/deploy-to-itunesconnect-deliver/2.7.3/step.yml

deploy-to-itunesconnect-deliver 2.7.3

---

steps/cocoapods-install/1.5.9/step.yml

cocoapods-install 1.5.9

---

steps/xcode-test-mac/1.0.6/step.yml

xcode-test-mac 1.0.6

---

steps/xcode-analyze/1.6.1/step.yml

xcode-analyze 1.6.1

---

steps/set-xcode-build-number/1.0.5/step.yml

set-xcode-build-number 1.0.5

---

steps/carthage/3.0.2/step.yml

carthage 3.0.2

---

steps/xcode-archive-mac/1.3.3/step.yml

xcode-archive-mac 1.3.3

---

steps/certificate-and-profile-installer/1.8.2/step.yml

certificate-and-profile-installer 1.8.2

---

steps/export-xcarchive-mac/0.9.2/step.yml

export-xcarchive-mac 0.9.2

---

steps/deploy-to-bitrise-io/1.2.6/step.yml

deploy-to-bitrise-io 1.2.6

---

steps/deploy-to-itunesconnect-deliver/2.8.0/step.yml

deploy-to-itunesconnect-deliver 2.8.0

---

steps/xamarin-archive/1.1.2/step.yml

xamarin-archive 1.1.2

---

steps/xamarin-test-cloud-for-ios/2.1.1/step.yml

xamarin-test-cloud-for-ios 2.1.1

---

steps/carthage/3.0.3/step.yml

carthage 3.0.3

---

steps/apk-info/1.2.0/step.yml

apk-info 1.2.0

---

steps/apk-info/1.2.1/step.yml

apk-info 1.2.1

---

steps/hockeyapp-deploy/2.4.0/step.yml

hockeyapp-deploy 2.4.0

---

steps/xamarin-archive/1.2.0/step.yml

xamarin-archive 1.2.0

---

steps/set-ios-info-plist-unified/1.1.4/step.yml

set-ios-info-plist-unified 1.1.4

---

steps/cocoapods-install/1.6.0/step.yml

cocoapods-install 1.6.0

---

steps/project-scanner/0.12.0/step.yml

project-scanner 0.12.0

---

steps/carthage/3.0.4/step.yml

carthage 3.0.4

---

steps/fastlane/2.3.0/step.yml

fastlane 2.3.0

---

steps/fastlane/2.3.1/step.yml

fastlane 2.3.1

---

steps/apk-info/1.2.2/step.yml

apk-info 1.2.2

---

steps/deploy-to-itunesconnect-deliver/2.8.1/step.yml

deploy-to-itunesconnect-deliver 2.8.1

---

steps/cocoapods-install/1.6.1/step.yml

cocoapods-install 1.6.1

---

steps/fastlane/2.3.3/step.yml

fastlane 2.3.3

---

steps/install-missing-android-tools/0.9.1/step.yml

install-missing-android-tools 0.9.1

---

steps/project-scanner/1.0.0/step.yml

project-scanner 1.0.0

---

steps/install-missing-android-tools/0.9.2/step.yml

install-missing-android-tools 0.9.2

---

steps/project-scanner/1.0.1/step.yml

project-scanner 1.0.1

---

steps/ftp-upload/2.0.2/step.yml

ftp-upload 2.0.2

---

steps/xamarin-archive/1.3.1/step.yml

xamarin-archive 1.3.1

---

steps/calabash-ios-uitest/1.2.1/step.yml

calabash-ios-uitest 1.2.1

---

steps/post-jira-comment-with-build-details/0.1.10/step.yml

post-jira-comment-with-build-details 0.1.10

---

steps/calabash-android-uitest/1.1.0/step.yml

calabash-android-uitest 1.1.0

---

steps/hipchat/3.0.3/step.yml

hipchat 3.0.3

---

steps/xamarin-test-cloud-for-calabash-android/1.0.0/step.yml

xamarin-test-cloud-for-calabash-android 1.0.0

---

steps/deploy-to-bitrise-io/1.2.7/step.yml

deploy-to-bitrise-io 1.2.7

---

steps/cache-pull/0.9.2/step.yml

cache-pull 0.9.2

---

steps/cache-push/0.9.4/step.yml

cache-push 0.9.4

---

steps/hockeyapp-deploy-android/1.1.1/step.yml

hockeyapp-deploy-android 1.1.1

---

steps/project-scanner/1.1.0/step.yml

project-scanner 1.1.0

---

steps/deploy-to-itunesconnect-deliver/2.8.2/step.yml

deploy-to-itunesconnect-deliver 2.8.2

---

steps/ftp-upload/2.0.3/step.yml

ftp-upload 2.0.3

---

steps/gradle-runner/1.5.3/step.yml

gradle-runner 1.5.3

---

steps/github-status/0.9.1/step.yml

github-status 0.9.1

---

steps/android-manifest-info/1.0.0/step.yml

android-manifest-info 1.0.0

---

steps/android-manifest-info/1.0.1/step.yml

android-manifest-info 1.0.1

---

steps/gradle-runner/1.5.4/step.yml

gradle-runner 1.5.4

---

steps/carthage/3.0.5/step.yml

carthage 3.0.5

---

steps/project-scanner/1.1.1/step.yml

project-scanner 1.1.1

---

steps/fastlane/2.3.4/step.yml

fastlane 2.3.4

---

steps/xamarin-ios-test/2.1.1/step.yml

xamarin-ios-test 2.1.1

---

steps/xamarin-archive/1.3.2/step.yml

xamarin-archive 1.3.2

---

steps/xcode-archive/2.0.5/step.yml

xcode-archive 2.0.5

---

steps/github-status/1.0.1/step.yml

github-status 1.0.1

---

steps/fastlane/2.3.5/step.yml

fastlane 2.3.5

---

steps/post-jira-comment-with-build-details/0.1.11/step.yml

post-jira-comment-with-build-details 0.1.11

---

steps/fastlane/2.3.6/step.yml

fastlane 2.3.6

---

steps/start-android-emulator/1.1.1/step.yml

start-android-emulator 1.1.1

---

steps/hipchat-v2/0.9.1/step.yml

hipchat-v2 0.9.1

---

steps/hipchat/3.0.4/step.yml

hipchat 3.0.4

---

steps/xamarin-android-test/1.0.0/step.yml

xamarin-android-test 1.0.0

---

steps/fastlane/2.3.7/step.yml

fastlane 2.3.7

---

steps/deploy-to-bitrise-io/1.2.8/step.yml

deploy-to-bitrise-io 1.2.8

---

steps/calabash-android-uitest/1.2.0/step.yml

calabash-android-uitest 1.2.0

---

steps/ftp-upload/2.0.4/step.yml

ftp-upload 2.0.4

---

steps/calabash-ios-uitest/1.3.0/step.yml

calabash-ios-uitest 1.3.0

---

_scripts/audit/audit_changed_steps.go
bitrise.yml

omit step-info.yml at audit

---

_scripts/audit/audit_changed_steps.go

log improvements

---

steps/project-scanner/1.1.2/step.yml

project-scanner 1.1.2

---

steps/generate-text-file/0.0.3/step.yml

Make generate text file step more resilient and add some output (helps narrowing down potential errors).

generate-text-file 0.0.3

---

steps/change-value/1.0.1/step.yml

change value step migration

---

steps/select-xcode-version/step-info.yml

Deprecate select-scode-version step

---

steps/deploy-to-bitrise-io/1.2.9/step.yml

deploy-to-bitrise-io 1.2.9

---

steps/xamarin-ios-test/2.2.0/step.yml

xamarin-ios-test 2.2.0

---

steps/xamarin-test-cloud-for-ios/2.2.0/step.yml

xamarin-test-cloud-for-ios 2.2.0

---

steps/xamarin-test-cloud-for-android/2.1.1/step.yml

xamarin-test-cloud-for-android 2.1.1

---

steps/certificate-and-profile-installer/1.8.3/step.yml
steps/select-xcode-version/step-info.yml

Certificate and profile installer 1.8.3

---

steps/git-clone/3.4.2/step.yml

git-clone 3.4.2

---

steps/calabash-ios-uitest/1.3.1/step.yml

calabash-ios-uitest 1.3.1

---

steps/calabash-android-uitest/1.2.1/step.yml

calabash-android-uitest 1.2.1

---

steps/carthage/3.0.6/step.yml

carthage 3.0.6

---

steps/xcode-archive-mac/1.4.0/step.yml

xcode-archive-mac 1.4.0

---

steps/react-native-bundle/1.0.3/step.yml

react-native-bundle 1.0.3

---

steps/certificate-and-profile-installer/1.8.4/step.yml

certificate-and-profile-installer 1.8.4

---

steps/xamarin-test-cloud-for-calabash-ios/1.0.0/step.yml

xamarin-test-cloud-for-calabash-ios 1.0.0

---

steps/project-scanner/1.1.3/step.yml

project-scanner 1.1.3

---

steps/codecov/1.1.4/step.yml

codecov 1.1.4

---

steps/github-status/1.0.3/step.yml

github-status 1.0.3

---

steps/codecov-android/step-info.yml

deprecate codecov-android step

---

steps/google-play-deploy/1.2.1/step.yml

google-play-deploy 1.2.1

---

steps/create-android-emulator/1.1.0/step.yml

create-android-emulator 1.1.0

---

steps/start-android-emulator/1.2.0/step.yml

start-android-emulator 1.2.0

---

steps/install-missing-android-tools/1.0.0/step.yml

install-missing-android-tools 1.0.0

---

steps/install-missing-android-tools/1.0.1/step.yml

install-missing-android-tools 1.0.1

---

steps/fastlane/2.3.9/step.yml

fastlane 2.3.9

---

steps/set-ios-product-bundle-identifier/1.1.0/step.yml

set-ios-product-bundle-identifier 1.1.0

---

steps/create-android-emulator/1.1.1/step.yml

create-android-emulator 1.1.1

---

steps/start-android-emulator/1.2.1/step.yml

start-android-emulator 1.2.1

---

steps/tslint/0.0.4/step.yml

tslint 0.0.4

---

steps/nunit-runner/1.2.0/step.yml

nunit-runner 1.2.0

---

steps/xcode-test/1.18.2/step.yml

xcode-test 1.18.2

---

steps/generate-gradle-wrapper/0.9.2/step.yml

generate-gradle-wrapper 0.9.2

---

steps/google-play-deploy/1.2.2/step.yml

google-play-deploy 1.2.2

---

steps/authenticate-host-with-netrc/0.9.0/step.yml

authenticate-host-with-netrc 0.9.0

---

steps/xcode-test/1.18.3/step.yml

xcode-test 1.18.3

---

steps/certificate-and-profile-installer/1.8.5/step.yml

certificate-and-profile-installer 1.8.5

---

steps/set-ios-product-bundle-identifier/1.1.2/step.yml

set-ios-product-bundle-identifier 1.1.2

---

steps/xamarin-archive/1.3.3/step.yml

xamarin-archive 1.3.3

---

steps/git-clone/3.4.3/step.yml

git-clone 3.4.3

---

steps/authenticate-with-github-oauth/0.9.0/step.yml

authenticate-with-github-oauth 0.9.0

---

steps/resign-ipa/1.2.2/step.yml

resign-ipa 1.2.2

---

steps/codified-security-bitrise/1.0.0/step.yml

codified-security-bitrise 1.0.0

---

steps/install-missing-android-tools/1.0.2/step.yml

install-missing-android-tools 1.0.2

---

steps/resign-ipa/step-info.yml

deprecate resign ipa

---

steps/deploy-to-itunesconnect-deliver/2.9.2/step.yml

deploy-to-itunesconnect-deliver 2.9.2

---

steps/authenticate-with-bitbucket-oauth/0.9.0/step.yml

authenticate-with-bitbucket-oauth 0.9.0

---

steps/deploy-to-itunesconnect-deliver/2.9.2/step.yml

Deploy to iTunes Connect tags

---

steps/cakebuild/1.0.0/step.yml

cakebuild 1.0.0

---

steps/cordova-archive/0.9.0/step.yml

cordova-archive 0.9.0

---

steps/karma-jasmine-runner/0.9.0/step.yml

karma-jasmine-runner 0.9.0

---

steps/jasmine-runner/0.9.0/step.yml

jasmine-runner 0.9.0

---

steps/sonarqube-scanner/1.0.0/step.yml

sonarqube-scanner 1.0.0

---

steps/cakebuild/1.0.1/step.yml

cakebuild 1.0.1

---

steps/cakebuild/1.0.2/step.yml

The step has been transferred to the Cake-Build community.

cakebuild 1.0.2

---

steps/sonarqube-scanner/assets/icon.svg

SonarQube Scanner step icon added

---

steps/cordova-archive/0.9.1/step.yml

cordova-archive 0.9.1

---

steps/karma-jasmine-runner/0.9.1/step.yml

karma-jasmine-runner 0.9.1

---

steps/cakebuild/1.0.3/step.yml

Added a fix when running .net core projects (openssl)

cakebuild 1.0.3

---

steps/post-jira-comment-with-build-details/0.1.12/step.yml

post-jira-comment-with-build-details 0.1.12

---

steps/dotnetcore/1.0.0/step.yml

dotnetcore 1.0.0

---

steps/build-number-adjust/1.0.0/step.yml

build-number-adjust 1.0.0

---

steps/create-android-emulator/1.1.2/step.yml

create-android-emulator 1.1.2

---

steps/gradle-runner/1.5.6/step.yml

gradle-runner 1.5.6

---

steps/project-scanner/1.2.1/step.yml

project-scanner 1.2.1

---

steps/project-scanner/1.2.2/step.yml

project-scanner 1.2.2

---

steps/start-android-emulator/1.3.0/step.yml

start-android-emulator 1.3.0

---

steps/slack/2.4.0/step.yml

slack 2.4.0

---

steps/slack/2.4.1/step.yml

slack 2.4.1

---

steps/sign-apk/1.1.2/step.yml

sign-apk 1.1.2

---

steps/aws-device-farm-file-deploy/0.0.3/step.yml

aws-device-farm-file-deploy 0.0.3

---

steps/create-android-emulator/1.1.3/step.yml

create-android-emulator 1.1.3

---

steps/start-android-emulator/1.3.1/step.yml

start-android-emulator 1.3.1

---

steps/project-scanner/1.2.3/step.yml

project-scanner 1.2.3

---

steps/xcode-archive-mac/1.4.1/step.yml

xcode-archive-mac 1.4.1

---

steps/recreate-user-schemes/1.0.0/step.yml

recreate-user-schemes 1.0.0

---

steps/project-scanner/1.2.4/step.yml

project-scanner 1.2.4

---

steps/slack/2.5.0/step.yml

slack 2.5.0

---

steps/recreate-user-schemes/1.0.1/step.yml

recreate-user-schemes 1.0.1

---

steps/nuget-restore/1.0.4/step.yml

nuget-restore 1.0.4

---

steps/create-android-emulator/1.1.4/step.yml

create-android-emulator 1.1.4

---

steps/deploy-to-bitrise-io/1.3.0/step.yml

deploy-to-bitrise-io 1.3.0

---

steps/cache-pull/0.9.4/step.yml

cache-pull 0.9.4

---

steps/cache-push/0.9.6/step.yml

cache-push 0.9.6

---

steps/deploy-to-bitrise-io/1.3.1/step.yml

deploy-to-bitrise-io 1.3.1

---

steps/codified-security-bitrise/1.0.1/step.yml

codified-security-bitrise 1.0.1

---

steps/cordova-archive/0.9.2/step.yml

cordova-archive 0.9.2

---

steps/ionic-archive/0.9.1/step.yml

ionic-archive 0.9.1

---

steps/cache-pull/1.0.0/step.yml

cache-pull 1.0.0

---

steps/cache-push/1.0.0/step.yml

cache-push 1.0.0

---

steps/gradle-runner/1.6.0/step.yml

gradle-runner 1.6.0

---

steps/deploy-to-bitrise-io/1.3.2/step.yml

deploy-to-bitrise-io 1.3.2

---

steps/gradle-runner/1.6.1/step.yml

gradle-runner 1.6.1

---

steps/deploy-to-bitrise-io/1.3.3/step.yml

deploy-to-bitrise-io 1.3.3

---

steps/ionic-archive/0.9.3/step.yml

ionic-archive 0.9.3

---

steps/gradle-runner/1.6.3/step.yml

gradle-runner 1.6.3

---

steps/android-sdk-update/1.0.4/step.yml

Fix https://github.com/guitcastro/steps-update-sdk/issues/8

android-sdk-update 1.0.4

---

steps/cache-push/1.1.0/step.yml

cache-push 1.1.0

---

steps/android-sdk-update/1.0.4/step.yml

android sdk update - tag normalization

---

steps/git-commit-changelog/1.0.2/step.yml

git-commit-changelog 1.0.2

---

steps/xamarin-archive/1.4.1/step.yml

xamarin-archive 1.4.1

---

steps/change-value/1.1.0/step.yml

change-value 1.1.0

---

steps/project-scanner/1.3.0/step.yml

project-scanner 1.3.0

---

steps/sonarqube-scanner/1.0.1/step.yml

sonarqube-scanner 1.0.1

---

steps/git-commit-changelog/1.0.3/step.yml

git-commit-changelog 1.0.3

---

steps/xcode-archive/2.0.6/step.yml

xcode-archive 2.0.6

---

steps/gradle-runner/1.7.0/step.yml

gradle-runner 1.7.0

---

steps/sign-apk/1.2.0/step.yml

sign-apk 1.2.0

---

steps/xcode-test/1.18.4/step.yml

xcode-test 1.18.4

---

steps/cocoapods-install/1.7.1/step.yml

cocoapods-install 1.7.1

---

steps/carthage/3.1.2/step.yml

carthage 3.1.2

---

steps/change-android-versioncode-and-versionname/0.9.0/step.yml

change-android-versioncode-and-versionname 0.9.0

---

steps/google-play-deploy/1.2.3/step.yml

google-play-deploy 1.2.3

---

steps/xamarin-user-management/1.1.0/step.yml

xamarin-user-management 1.1.0

---

steps/project-scanner/1.4.0/step.yml

project-scanner 1.4.0

---

steps/install-missing-android-tools/1.0.3/step.yml

install-missing-android-tools 1.0.3

---

steps/xamarin-archive/1.4.2/step.yml

xamarin-archive 1.4.2

---

steps/certificate-and-profile-installer/1.8.6/step.yml

certificate-and-profile-installer 1.8.6

---

steps/script/1.1.4/step.yml

script 1.1.4

---

steps/git-clone/3.4.4/step.yml

git-clone 3.4.4

---

steps/deploy-to-bitrise-io/1.3.4/step.yml

deploy-to-bitrise-io 1.3.4

---

steps/xcode-test/1.18.5/step.yml

xcode-test 1.18.5

---

steps/project-scanner/1.4.1/step.yml

project-scanner 1.4.1

---

steps/deploy-to-bitrise-io/1.3.5/step.yml

deploy-to-bitrise-io 1.3.5

---

steps/aws-device-farm-file-deploy/0.0.4/step.yml

***
* Export ARN of uploaded file
* Update docs to try to make relationship to aws-device-farm-runner more clear & link setup instructions wiki
* Update type tags again

aws-device-farm-file-deploy 0.0.4

---

steps/create-android-emulator/1.1.5/step.yml

create-android-emulator 1.1.5

---

steps/git-clone/3.5.0/step.yml

git-clone 3.5.0

---

steps/cache-push/1.1.1/step.yml

cache-push 1.1.1

---

steps/gradle-runner/1.7.1/step.yml

gradle-runner 1.7.1

---

steps/set-ios-info-plist-unified/1.1.6/step.yml

- [*] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [*] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [*] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [*] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

set-ios-info-plist-unified 1.1.6

---

steps/nunit-runner/1.3.0/step.yml

nunit-runner 1.3.0

---

steps/xamarin-android-test/1.1.0/step.yml

xamarin-android-test 1.1.0

---

steps/xamarin-ios-test/2.3.1/step.yml

xamarin-ios-test 2.3.1

---

steps/xamarin-test-cloud-for-android/2.2.0/step.yml

xamarin-test-cloud-for-android 2.2.0

---

steps/xamarin-test-cloud-for-ios/2.3.0/step.yml

xamarin-test-cloud-for-ios 2.3.0

---

steps/vpnc-connect/1.0.0/step.yml

vpnc-connect 1.0.0

---

steps/codified-security-bitrise/2.0.0/step.yml

codified-security-bitrise 2.0.0

---

steps/apk-info/1.2.3/step.yml

apk-info 1.2.3

---

steps/hockeyapp-deploy/2.4.2/step.yml

hockeyapp-deploy 2.4.2

---

steps/project-scanner/1.4.2/step.yml

project-scanner 1.4.2

---

steps/gradle-unit-test/1.0.2/step.yml

gradle-unit-test 1.0.2

---

steps/cache-push/1.1.3/step.yml

cache-push 1.1.3

---

steps/deploy-to-itunesconnect-deliver/2.9.4/step.yml

deploy-to-itunesconnect-deliver 2.9.4

---

steps/deploy-to-bitrise-io/1.3.6/step.yml

deploy-to-bitrise-io 1.3.6

---

steps/project-scanner/1.5.0/step.yml

project-scanner 1.5.0

---

steps/gradle-runner/1.7.2/step.yml

gradle-runner 1.7.2

---

steps/git-clone/3.5.1/step.yml

git-clone 3.5.1

---

steps/android-sdk-update/1.0.6/step.yml

Fix [Step fails for 1.0.4](https://github.com/guitcastro/steps-update-sdk/issues/11)

android-sdk-update 1.0.6

---

steps/gradle-runner/1.7.3/step.yml

gradle-runner 1.7.3

---

steps/xcode-archive/2.1.0/step.yml

xcode-archive 2.1.0

---

steps/certificate-and-profile-installer/1.8.7/step.yml

certificate-and-profile-installer 1.8.7

---

steps/project-scanner/1.5.2/step.yml

project-scanner 1.5.2

---

steps/xcode-test/1.18.6/step.yml

xcode-test 1.18.6

---

steps/gradle-runner/1.7.5/step.yml

gradle-runner 1.7.5

---

steps/gradle-runner/1.7.6/step.yml

gradle-runner 1.7.6

---

steps/aws-device-farm-runner/0.0.6/step.yml

aws-device-farm-runner 0.0.6

---

steps/gradle-unit-test/1.0.3/step.yml

gradle-unit-test 1.0.3

---

steps/cache-push/1.1.4/step.yml

cache-push 1.1.4

---

steps/slack/2.6.1/step.yml

slack 2.6.1

---

steps/xcode-test/1.18.7/step.yml

xcode-test 1.18.7

---

steps/git-commit-changelog/1.0.4/step.yml

git-commit-changelog 1.0.4

---

steps/xamarin-archive/1.5.0/step.yml

xamarin-archive 1.5.0

---

steps/xamarin-android-test/1.2.0/step.yml

xamarin-android-test 1.2.0

---

steps/xamarin-ios-test/2.4.0/step.yml

xamarin-ios-test 2.4.0

---

steps/xamarin-test-cloud-for-android/2.3.0/step.yml

xamarin-test-cloud-for-android 2.3.0

---

steps/xamarin-test-cloud-for-ios/2.4.0/step.yml

xamarin-test-cloud-for-ios 2.4.0

---

steps/nunit-runner/1.4.0/step.yml

nunit-runner 1.4.0

---

steps/ionic-archive/0.9.4/step.yml

ionic-archive 0.9.4

---

steps/cordova-archive/0.9.3/step.yml

cordova-archive 0.9.3

---

steps/ftp-upload/2.1.1/step.yml

ftp-upload 2.1.1

---

steps/ftp-upload/2.1.2/step.yml

ftp-upload 2.1.2

---

steps/install-missing-android-tools/1.1.0/step.yml

install-missing-android-tools 1.1.0

---

steps/project-scanner/1.5.3/step.yml

project-scanner 1.5.3

---

steps/certificate-and-profile-installer/1.8.8/step.yml

certificate-and-profile-installer 1.8.8

---

steps/project-scanner/1.5.4/step.yml

project-scanner 1.5.4

---

steps/ftp-upload/2.1.3/step.yml

ftp-upload 2.1.3

---

steps/xcode-archive-mac/1.5.1/step.yml

xcode-archive-mac 1.5.1

---

steps/xcode-archive/2.1.1/step.yml

xcode-archive 2.1.1

---

steps/project-scanner/1.5.5/step.yml

project-scanner 1.5.5

---

steps/lifx-notifier/1.0.3/step.yml

Same as https://github.com/bitrise-io/bitrise-steplib/pull/1143 + `type_tags` adjustment.

lifx-notifier 1.0.3

---

steps/firebase-testlab/0.9.0/step.yml

firebase-testlab 0.9.0

---

steps/git-commit-changelog/1.0.5/step.yml

git-commit-changelog 1.0.5

---

steps/apk-info/1.3.0/step.yml

apk-info 1.3.0

---

steps/aws-device-farm-runner/0.0.7/step.yml

* Incorporate patch from crysxd: [Feature/locale support](https://github.com/peartherapeutics/bitrise-aws-device-farm-runner/pull/44)

aws-device-farm-runner 0.0.7

---

steps/install-missing-android-tools/2.0.0/step.yml

install-missing-android-tools 2.0.0

---

steps/recreate-user-schemes/1.0.2/step.yml

recreate-user-schemes 1.0.2

---

steps/project-scanner/1.5.6/step.yml

project-scanner 1.5.6

---

steps/install-missing-android-tools/2.0.1/step.yml

install-missing-android-tools 2.0.1

---

steps/slack/2.6.2/step.yml

slack 2.6.2

---

steps/virtual-device-testing-for-android/0.9.5/step.yml

virtual-device-testing-for-android 0.9.5

---

steps/project-scanner/1.5.7/step.yml

project-scanner 1.5.7

---

steps/xcode-archive/2.2.0/step.yml

xcode-archive 2.2.0

---

steps/script-runner/0.9.2/step.yml

script-runner 0.9.2

---

steps/deploy-to-bitrise-io/1.3.7/step.yml

deploy-to-bitrise-io 1.3.7

---

steps/bitbucket-snippet-runner/0.1.0/step.yml

bitbucket-snippet-runner 0.1.0

---

steps/xcode-archive/2.2.1/step.yml

xcode-archive 2.2.1

---

steps/install-missing-android-tools/2.0.2/step.yml

install-missing-android-tools 2.0.2

---

steps/gradle-runner/1.7.7/step.yml

gradle-runner 1.7.7

---

steps/git-clone/3.5.2/step.yml

git-clone 3.5.2

---

steps/ionic-archive/0.9.5/step.yml

ionic-archive 0.9.5

---

steps/openstf-connect/0.0.2/step.yml

openstf-connect 0.0.2

---

steps/swiftlint/0.1.1/step.yml

swiftlint 0.1.1

---

steps/recursive-touch/0.9.0/step.yml

recursive-touch 0.9.0

---

steps/xcode-archive/2.3.0/step.yml

xcode-archive 2.3.0

---

steps/bitbucket-snippet-runner/1.0.0/step.yml

bitbucket-snippet-runner 1.0.0

---

steps/git-last-commit-date/1.0.0/step.yml

git-last-commit-date 1.0.0

---

steps/xcode-archive/2.3.1/step.yml

xcode-archive 2.3.1

---

steps/ionic-archive/0.10.0/step.yml

ionic-archive 0.10.0

---

steps/bitbucket-snippet-runner/1.1.0/step.yml

bitbucket-snippet-runner 1.1.0 (ability to add scripts args)

---

steps/virtual-device-testing-for-android/0.9.6/step.yml

virtual-device-testing-for-android 0.9.6

---

steps/ionic-archive/1.0.0/step.yml

ionic-archive 1.0.0

---

steps/cache-push/2.0.0/step.yml

cache-push 2.0.0

---

steps/cache-pull/2.0.0/step.yml

cache-pull 2.0.0

---

steps/project-scanner/1.5.8/step.yml

project-scanner 1.5.8

---

steps/virtual-device-testing-for-android/0.9.7/step.yml

virtual-device-testing-for-android 0.9.7

---

steps/cache-push/2.0.1/step.yml

cache-push 2.0.1

---

steps/xcode-archive-mac/1.5.2/step.yml

xcode-archive-mac 1.5.2

---

steps/swiftlint/0.2.1/step.yml

swiftlint 0.2.1

---

steps/deploy-to-itunesconnect-deliver/2.9.5/step.yml

deploy-to-itunesconnect-deliver 2.9.5

---

steps/certificate-and-profile-installer/1.9.0/step.yml

certificate-and-profile-installer 1.9.0

---

steps/script-runner/0.9.3/step.yml

script-runner 0.9.3

---

steps/xcode-archive/2.3.2/step.yml

xcode-archive 2.3.2

---

steps/cordova-archive/1.0.0/step.yml

cordova-archive 1.0.0

---

steps/swiftlint/0.3.0/step.yml

swiftlint 0.3.0 - added reporter to config

---

steps/certificate-and-profile-installer/1.9.1/step.yml

certificate-and-profile-installer 1.9.1

---

steps/xcode-archive/2.3.3/step.yml

xcode-archive 2.3.3

---

steps/xcode-test/1.18.8/step.yml

xcode-test 1.18.8

---

steps/bitrise-run/0.9.0/step.yml

bitrise-run 0.9.0

---

steps/install-missing-android-tools/2.0.3/step.yml

install-missing-android-tools 2.0.3

---

steps/hockeyapp-deploy-android/1.1.4/step.yml

hockeyapp-deploy-android 1.1.4

---

steps/deploy-to-bitrise-io/1.3.8/step.yml

deploy-to-bitrise-io 1.3.8

---

steps/swiftlint/0.3.1/step.yml

swiftlint 0.3.1 bug fixes

---

steps/deploy-to-itunesconnect-deliver/2.10.0/step.yml

deploy-to-itunesconnect-deliver 2.10.0

---

steps/ionic-archive/1.1.0/step.yml

ionic-archive 1.1.0

---

steps/gradle-runner/1.7.8/step.yml

gradle-runner 1.7.8

---

steps/virtual-device-testing-for-android/0.9.8/step.yml

virtual-device-testing-for-android 0.9.8

---

steps/certificate-and-profile-installer/1.9.2/step.yml

certificate-and-profile-installer 1.9.2

---

steps/xcode-archive/2.3.6/step.yml

xcode-archive 2.3.6

---

steps/nuget-restore/1.0.5/step.yml

nuget-restore 1.0.5

---

steps/fastlane-match/0.0.2/step.yml

fastlane-match 0.0.2

---

steps/gradle-runner/1.8.0/step.yml

gradle-runner 1.8.0

---

steps/xcode-archive/2.3.7/step.yml

xcode-archive 2.3.7

---

steps/script/1.1.5/step.yml

script 1.1.5

---

steps/cocoapods-install/1.7.2/step.yml

cocoapods-install 1.7.2

---

steps/install-missing-android-tools/2.0.4/step.yml

install-missing-android-tools 2.0.4

---

steps/brew-install/0.9.0/step.yml

brew-install 0.9.0

---

steps/apt-get-install/0.9.0/step.yml

apt-get-install 0.9.0

---

steps/git-clone/3.5.3/step.yml

git-clone 3.5.3

---

steps/slack/2.6.3/step.yml

slack 2.6.3

---

steps/deploy-to-itunesconnect-deliver/2.11.0/step.yml

deploy-to-itunesconnect-deliver 2.11.0

---

steps/telegram-notifier/1.0.0/step.yml

telegram-notifier 1.0.0

---

steps/set-env-var/0.9.0/step.yml

set-env-var 0.9.0

---

steps/install-missing-android-tools/2.0.5/step.yml

install-missing-android-tools 2.0.5

---

steps/google-play-deploy/1.3.1/step.yml

google-play-deploy 1.3.1

---

steps/google-play-deploy/1.3.2/step.yml

google-play-deploy 1.3.2

---

steps/ios-auto-provision/0.9.0/step.yml

ios-auto-provision 0.9.0

---

steps/ios-auto-provision/0.9.1/step.yml

ios-auto-provision 0.9.1

---

steps/ios-auto-provision/0.9.2/step.yml

ios-auto-provision 0.9.2

---

steps/fastlane-match/0.1.0/step.yml

fastlane-match 0.1.0

---

steps/git-clone/3.6.0/step.yml

git-clone 3.6.0

---

steps/ionic-archive/1.2.1/step.yml

ionic-archive 1.2.1

---

steps/git-clone/3.6.1/step.yml

git-clone 3.6.1

---

steps/git-clone/3.6.2/step.yml

git-clone 3.6.2

---

steps/swiftlint/0.4.0/step.yml

Adds Swiftlint `--strict` flag

swiftlint 0.4.0

---

steps/swiftlint/0.4.2/step.yml

@viktorbenei and @deanWombourne if this I wrong, I'm just going to sleep ! xD
And I'm really sorry for all the work @viktorbenei !

Swiftlint 0.4.2 😴😴😴

---

steps/start-android-emulator/1.3.2/step.yml

start-android-emulator 1.3.2

---

steps/diawi-upload/0.0.3/step.yml

Updates from @kdobmayer - no other changes :)

diawi-upload 0.0.3

---

steps/xcode-archive/2.4.0/step.yml

xcode-archive 2.4.0

---

steps/xcode-archive/2.4.1/step.yml

xcode-archive 2.4.1

---

steps/deploy-to-bitrise-io/1.3.9/step.yml

deploy-to-bitrise-io 1.3.9

---

steps/xcode-analyze/1.7.1/step.yml

xcode-analyze 1.7.1

---

steps/export-xcarchive-mac/1.0.2/step.yml

export-xcarchive-mac 1.0.2

---

steps/xcode-archive/2.4.2/step.yml

xcode-archive 2.4.2

---

steps/xcode-archive-mac/1.6.0/step.yml

xcode-archive-mac 1.6.0

---

steps/cache-push/2.0.3/step.yml

cache-push 2.0.3
