bitrise-io/bitrise-steplib

steps/export-xcarchive/1.0.0/step.yml

export-xcarchive 1.0.0

---

steps/set-ios-version/2.0.0/step.yml

I hope everything is fixed.
@viktorbenei

set-ios-version 2.0.0

---

steps/google-play-deploy/1.3.3/step.yml

google-play-deploy 1.3.3

---

steps/openstf-connect/0.0.3/step.yml

openstf-connect 0.0.3

---

steps/openstf-connect/0.0.4/step.yml

openstf-connect 0.0.4

---

steps/diawi-upload/0.0.4/step.yml

Add an output to the log for the uploaded url

diawi-upload 0.0.4

---

steps/avd-manager/0.9.1/step.yml

avd-manager 0.9.1

---

steps/trigger-bitrise-workflow/0.0.1/step.yml

trigger-bitrise-workflow 0.0.1

---

steps/install-missing-android-tools/2.0.6/step.yml

install-missing-android-tools 2.0.6

---

steps/carthage/3.1.3/step.yml

carthage 3.1.3

---

steps/cache-pull/2.0.1/step.yml

cache-pull 2.0.1

---

steps/ios-auto-provision/0.9.3/step.yml

ios-auto-provision 0.9.3

---

steps/ios-auto-provision/0.9.4/step.yml

ios-auto-provision 0.9.4

---

steps/hockeyapp-deploy-android/1.2.1/step.yml

hockeyapp-deploy-android 1.2.1

---

steps/xcode-archive/2.4.3/step.yml

xcode-archive 2.4.3

---

steps/xcode-archive-mac/1.6.1/step.yml

xcode-archive-mac 1.6.1

---

steps/cordova-config/0.0.3/step.yml

cordova-config 0.0.3

---

steps/xcode-test/1.18.9/step.yml

xcode-test 1.18.9

---

steps/openstf-connect/0.0.5/step.yml

openstf-connect 0.0.5

---

steps/xcode-test-mac/1.1.2/step.yml

xcode-test-mac 1.1.2

---

steps/trigger-bitrise-workflow/assets/icon.svg

Add trigger-bitrise-workflow icon

---

steps/project-scanner/1.6.0/step.yml

project-scanner 1.6.0

---

steps/virtual-device-testing-for-android/0.9.9/step.yml

virtual-device-testing-for-android 0.9.9

---

steps/git-clone/4.0.1/step.yml

git-clone 4.0.1

---

steps/git-clone/4.0.3/step.yml

git-clone 4.0.3

---

steps/git-clone/4.0.4/step.yml

git-clone 4.0.4

---

steps/set-ios-product-bundle-identifier/1.1.3/step.yml

set-ios-product-bundle-identifier 1.1.3

---

steps/deploy-to-bitrise-io/1.3.10/step.yml

deploy-to-bitrise-io 1.3.10

---

steps/appcenter-dsym-upload/0.1.2/step.yml

appcenter-dsym-upload 0.1.2

---

steps/cordova-archive/1.0.1/step.yml

cordova-archive 1.0.1

---

steps/fastlane/2.3.11/step.yml

fastlane 2.3.11

---

steps/avd-manager/0.9.2/step.yml

avd-manager 0.9.2

---

steps/hipchat/3.1.0/step.yml

hipchat 3.1.0

---

steps/android-screenrecord-stop/0.9.0/step.yml

android-screenrecord-stop 0.9.0

---

steps/android-screenrecord-start/0.9.0/step.yml

android-screenrecord-start 0.9.0

---

steps/export-xcarchive/1.0.1/step.yml

export-xcarchive 1.0.1

---

steps/virtual-device-testing-for-android/1.0.0/step.yml

virtual-device-testing-for-android 1.0.0

---

steps/git-clone/4.0.5/step.yml

git-clone 4.0.5

---

steps/fastlane/2.3.12/step.yml

fastlane 2.3.12

---

steps/project-scanner/1.6.1/step.yml

project-scanner 1.6.1

---

steps/ios-auto-provision/0.9.5/step.yml

ios-auto-provision 0.9.5

---

steps/project-scanner/1.6.2/step.yml

project-scanner 1.6.2

---

steps/xcode-archive/2.4.4/step.yml

xcode-archive 2.4.4

---

steps/email-with-mailgun/2.1.1/step.yml

email-with-mailgun 2.1.1

---

steps/hipchat-v2/1.0.1/step.yml

hipchat-v2 1.0.1

---

steps/deploy-to-itunesconnect-deliver/2.12.0/step.yml

deploy-to-itunesconnect-deliver 2.12.0

---

steps/ios-auto-provision/0.9.6/step.yml

ios-auto-provision 0.9.6

---

steps/install-missing-android-tools/2.1.0/step.yml

install-missing-android-tools 2.1.0

---

bitrise.yml

Deploy slimjson

---

steps/ipa-info/1.1.0/step.yml

Ipa info 1.1.0

---

steps/activate-ssh-key/3.1.1/step.yml
steps/android-manifest-info/1.0.1/step.yml
steps/avd-manager/0.9.2/step.yml
steps/bitrise-artifact-deploy/0.9.0/step.yml
steps/cocoapods-and-repository-validator/4.3.1/step.yml
steps/hipchat/3.1.0/step.yml
steps/nunit-runner/1.4.0/step.yml
steps/resign-ipa/1.2.2/step.yml
steps/sign-apk/1.2.0/step.yml
steps/xamarin-builder/1.4.2/step.yml

Update type_tags and project_type_tags

---

steps/xcode-archive/2.4.5/step.yml

xcode-archive 2.4.5

---

steps/xcode-archive-mac/1.6.2/step.yml

xcode-archive-mac 1.6.2

---

steps/google-play-deploy/1.4.1/step.yml

google-play-deploy 1.4.1

---

steps/change-android-versioncode-and-versionname/1.0.0/step.yml

change-android-versioncode-and-versionname 1.0.0

---

steps/ios-auto-provision/0.9.7/step.yml

ios-auto-provision 0.9.7

---

steps/xcode-test/1.18.10/step.yml

xcode-test 1.18.10

---

steps/cache-push/2.0.4/step.yml

cache-push 2.0.4

---

steps/gradle-runner/1.8.1/step.yml

gradle-runner 1.8.1

---

steps/git-clone/4.0.6/step.yml

git-clone 4.0.6

---

steps/cache-push/2.0.5/step.yml

cache-push 2.0.5

---

steps/slack/2.6.4/step.yml

slack 2.6.4

---

steps/install-missing-android-tools/2.1.1/step.yml

install-missing-android-tools 2.1.1

---

steps/git-clone/4.0.7/step.yml

git-clone 4.0.7

---

steps/virtual-device-testing-for-android/1.0.1/step.yml

virtual-device-testing-for-android 1.0.1

---

steps/xcode-test/1.18.11/step.yml

xcode-test 1.18.11

---

steps/slack/2.6.5/step.yml

slack 2.6.5

---

steps/apk-info/1.4.0/step.yml

apk-info 1.4.0

---

steps/app-center-launch-test-android/1.0.0/step.yml

app-center-launch-test-android 1.0.0

---

steps/bitbucket-snippet-runner/1.1.1/step.yml

bitbucket-snippet-runner 1.1.1

---

steps/bitrise-run/0.9.1/step.yml

bitrise-run 0.9.1

---

steps/gradle-runner/1.8.2/step.yml

gradle-runner 1.8.2

---

steps/xcode-archive/2.4.6/step.yml

xcode-archive 2.4.6

---

steps/resource-archive/2.0.1/step.yml

resource-archive 2.0.1

---

steps/sonarqube-scanner/1.0.2/step.yml

sonarqube-scanner 1.0.2

---

steps/authenticate-host-with-netrc/0.9.2/step.yml

authenticate-host-with-netrc 0.9.2

---

steps/cordova-archive/1.1.0/step.yml

cordova-archive 1.1.0

---

steps/gradle-runner/1.8.3/step.yml

gradle-runner 1.8.3

---

_scripts/audit_icons/audit_icons.go
bitrise.yml

added task to check icon existence

---

steps/gradle-unit-test/1.0.5/step.yml

gradle-unit-test 1.0.5

---

steps/xcode-test/1.18.12/step.yml

Typo fix: https://github.com/bitrise-io/steps-xcode-test/pull/86

xcode-test 1.18.12

---

steps/slack/2.7.1/step.yml

slack 2.7.1

---

steps/slack/2.7.2/step.yml

slack 2.7.2

---

steps/github-status/1.0.4/step.yml

github-status 1.0.4

---

steps/appcenter-dsym-upload/0.1.3/step.yml

Appcenter dsym upload 0.1.3

---

steps/git-clone/4.0.8/step.yml

git-clone 4.0.8

---

steps/gitlab-status/0.9.0/step.yml

gitlab-status 0.9.0

---

steps/wetransfer/0.0.5/step.yml

wetransfer 0.0.5

---

steps/github-status/1.1.0/step.yml

github-status 1.1.0

---

steps/gitlab-status/0.9.1/step.yml

gitlab-status 0.9.1

---

steps/twitter-message/0.0.4/step.yml

twitter-message 0.0.4

---

steps/file-downloader/1.0.0/step.yml

file-downloader 1.0.0

---

steps/deploy-to-itunesconnect-deliver/2.13.0/step.yml

deploy-to-itunesconnect-deliver 2.13.0

---

steps/gitlab-status/0.9.2/step.yml

gitlab-status 0.9.2

---

steps/git-clone/4.0.9/step.yml

git-clone 4.0.9

---

steps/update-jira-issue-field/1.0.1/step.yml

update-jira-issue-field 1.0.1

---

steps/xcode-test/1.18.13/step.yml

xcode-test 1.18.13

---

steps/cordova-archive/1.1.1/step.yml

cordova-archive 1.1.1

---

steps/github-status/1.1.1/step.yml

github-status 1.1.1

---

steps/trigger-bitrise-workflow/0.0.2/step.yml

trigger-bitrise-workflow 0.0.2

---

steps/gitlab-status/assets/icon.svg

Add gitlab-status step's icon

---

steps/gitlab-status/0.9.3/step.yml

gitlab-status 0.9.3

---

steps/cakebuild/1.0.0/step.yml
steps/cakebuild/1.0.1/step.yml
steps/cakebuild/1.0.4/step.yml

Cakebuild 1.0.4

---

steps/detekt/1.0.0/step.yml

Detekt 1.0.0

---

steps/cakebuild/1.0.0/step.yml
steps/cakebuild/1.0.1/step.yml
steps/cakebuild/1.0.5/step.yml

Cakebuild 1.0.5

---

steps/cakebuild/1.0.0/step.yml
steps/cakebuild/1.0.1/step.yml
steps/cakebuild/1.0.6/step.yml

Cakebuild 1.0.6

---

steps/cakebuild/1.0.7/step.yml

cakebuild 1.0.7

---

steps/github-status/2.0.0/step.yml

github-status 2.0.0

---

steps/ionic-archive/1.2.2/step.yml

ionic-archive 1.2.2

---

steps/github-status/2.1.0/step.yml

github-status 2.1.0

---

steps/gitlab-status/0.9.5/step.yml

gitlab-status 0.9.5

---

steps/deploy-to-itunesconnect-shenzhen/step-info.yml

Deprecate itunesconnect-shenzhen step

---

steps/git-clone/4.0.10/step.yml

git-clone 4.0.10

---

steps/google-play-deploy/1.4.2/step.yml

google-play-deploy 1.4.2

---

steps/dropbox/1.0.3/step.yml

dropbox 1.0.3

---

steps/appcenter-codepush-release-react-native/0.0.1/step.yml
steps/appcenter-codepush-release-react-native/assets/icon.svg

appcenter-codepush-release-react-native 0.0.1

---

steps/parse-composer-results/0.0.1/step.yml

parse-composer-results 0.0.1

---

steps/android-screenrecord-start/step-info.yml
steps/android-screenrecord-stop/step-info.yml
steps/firebase-testlab/step-info.yml

Steps deprecation

---

steps/parse-composer-results/0.0.2/step.yml

parse-composer-results 0.0.2

---

steps/deploy-to-itunesconnect-deliver/2.13.1/step.yml

deploy-to-itunesconnect-deliver 2.13.1

---

steps/fabric-crashlytics-beta-deploy/2.2.3/step.yml

fabric-crashlytics-beta-deploy 2.2.3

---

steps/wetransfer/step-info.yml

feat(wetransfer-step):deprecated

---

steps/twitter-message/1.0.2/step.yml

twitter-message 1.0.2

---

steps/google-play-deploy/1.4.3/step.yml

google-play-deploy 1.4.3

---

steps/ios-auto-provision/1.0.1/step.yml

ios-auto-provision 1.0.1

---

steps/android-build/0.9.1/step.yml

android-build 0.9.1

---

steps/android-unit-test/0.9.0/step.yml
steps/android-unit-test/assets/icon.svg

android-unit-test 0.9.0

---

steps/deploy-to-itunesconnect-deliver/2.13.2/step.yml

deploy-to-itunesconnect-deliver 2.13.2

---

steps/xcode-test-mac/1.2.1/step.yml

xcode-test-mac 1.2.1

---

steps/amazon-s3-deploy/3.5.3/step.yml

amazon-s3-deploy 3.5.3

---

steps/email-with-mailgun/2.1.2/step.yml

email-with-mailgun 2.1.2

---

steps/nuget-restore/1.0.6/step.yml

nuget-restore 1.0.6

---

bitrise.yml

separated slim-spec.gz

---

steps/ionic-archive/1.2.3/step.yml

ionic-archive 1.2.3

---

steps/amazon-s3-deploy/3.5.4/step.yml

amazon-s3-deploy 3.5.4

---

steps/cakebuild/1.0.8/step.yml

- [x I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)

cakebuild 1.0.8

---

steps/twitter-message/1.0.4/step.yml

twitter-message 1.0.4

---

steps/cakebuild/1.0.9/step.yml

cakebuild 1.0.9

---

steps/build-router-start/0.9.0/step.yml
steps/build-router-start/assets/icon.svg

Build router start 0.9.0

---

steps/trigger-bitrise-workflow/0.0.3/step.yml

trigger-bitrise-workflow 0.0.3

---

steps/build-router-wait/0.9.0/step.yml
steps/build-router-wait/assets/icon.svg

build-router-wait 0.9.0

---

steps/flutter/0.0.1/step.yml

flutter 0.0.1

---

steps/android-unit-test/0.9.2/step.yml

android-unit-test 0.9.2

---

steps/ios-auto-provision/1.0.2/step.yml

ios-auto-provision 1.0.2

---

steps/nuget-restore/1.0.7/step.yml

nuget-restore 1.0.7

---

steps/flutter/assets/icon.svg

Add Flutter step icon

---

steps/appcenter-test/0.9.0/step.yml
steps/appcenter-test/assets/icon.svg

appcenter-test 0.9.0

---

steps/virtual-device-testing-for-android/1.0.2/step.yml

virtual-device-testing-for-android 1.0.2

---

steps/post-jira-comment-with-build-details/1.0.0/step.yml

post-jira-comment-with-build-details 1.0.0

---

steps/android-lint/0.9.1/step.yml

android-lint 0.9.1

---

steps/android-build/0.9.2/step.yml

android-build 0.9.2

---

steps/flutter/0.0.2/step.yml

flutter 0.0.2

---

steps/flutter/0.0.3/step.yml

flutter 0.0.3

---

steps/xcode-test/1.18.14/step.yml

xcode-test 1.18.14

---

steps/carthage/3.1.4/step.yml

carthage 3.1.4

---

steps/xcode-archive/2.4.7/step.yml

xcode-archive 2.4.7

---

steps/deploy-to-bitrise-io/1.3.11/step.yml

deploy-to-bitrise-io 1.3.11

---

steps/certificate-and-profile-installer/1.9.3/step.yml

certificate-and-profile-installer 1.9.3

---

steps/ionic-archive/1.2.4/step.yml

ionic-archive 1.2.4

---

steps/ios-auto-provision/1.0.3/step.yml

ios-auto-provision 1.0.3

---

steps/random-quote/3.0.3/step.yml

random-quote 3.0.3

---

steps/xcode-archive/2.4.8/step.yml

xcode-archive 2.4.8

---

steps/android-build/0.9.3/step.yml

android-build 0.9.3

---

steps/ios-auto-provision/1.1.0/step.yml

ios-auto-provision 1.1.0

---

steps/authenticate-host-with-netrc/0.9.3/step.yml
steps/authenticate-host-with-netrc/assets/icon.svg

authenticate-host-with-netrc 0.9.3

---

steps/cordova-prepare/0.9.2/step.yml

cordova-prepare 0.9.2

---

steps/deploy-to-bitrise-io/1.3.12/step.yml

deploy-to-bitrise-io 1.3.12

---

steps/generic-file-storage/0.9.0/step.yml
steps/generic-file-storage/assets/icon.svg

generic-file-storage 0.9.0

---

steps/android-build/0.9.4/step.yml

android-build 0.9.4

---

steps/android-lint/0.9.2/step.yml

android-lint 0.9.2

---

steps/android-unit-test/0.9.3/step.yml

android-unit-test 0.9.3

---

steps/sonarqube-scanner/1.0.3/step.yml

sonarqube-scanner 1.0.3

---

steps/flutter/0.0.4/step.yml

flutter 0.0.4

---

steps/xamarin-insights/step-info.yml

Add step-info about deprecation for xamarin-insights

---

steps/ionic-prepare/0.9.0/step.yml
steps/ionic-prepare/assets/icon.svg

ionic-prepare 0.9.0

---

steps/activate-ssh-key/4.0.1/step.yml

activate-ssh-key 4.0.1

---

steps/deploy-to-itunesconnect-deliver/2.14.0/step.yml

deploy-to-itunesconnect-deliver 2.14.0

---

steps/activate-ssh-key/4.0.2/step.yml

activate-ssh-key 4.0.2

---

steps/appetize-deploy/0.9.0/step.yml

appetize-deploy 0.9.0

---

steps/sign-apk/1.2.1/step.yml

sign-apk 1.2.1

---

steps/xcode-archive/2.4.9/step.yml

xcode-archive 2.4.9

---

steps/git-tag-project-version-and-build-number/1.0.0/step.yml

git-tag-project-version-and-build-number 1.0.0

---

steps/slack/2.7.3/step.yml

slack 2.7.3

---

steps/trigger-bitrise-workflow/0.0.4/step.yml

trigger-bitrise-workflow 0.0.4

---

steps/github-release/0.9.1/step.yml

github-release 0.9.1

---

steps/generate-changelog/0.9.0/step.yml

generate-changelog 0.9.0

---

steps/ios-auto-provision/1.1.3/step.yml

ios-auto-provision 1.1.3

---

steps/git-tag-project-version-and-build-number/1.0.1/step.yml

git-tag-project-version-and-build-number 1.0.1

---

steps/xcode-test/1.18.15/step.yml

xcode-test 1.18.15

---

steps/file-downloader/1.0.1/step.yml

file-downloader 1.0.1

---

steps/deploy-to-itunesconnect-application-loader/0.9.2/step.yml

deploy-to-itunesconnect-application-loader 0.9.2

---

steps/feature-list-for-release-notes/0.0.1/step.yml

feature-list-for-release-notes 0.0.1

---

steps/testfairy-deploy/2.1.1/step.yml

testfairy-deploy 2.1.1

---

steps/certificate-and-profile-installer/1.10.0/step.yml

certificate-and-profile-installer 1.10.0

---

steps/go-test/1.0.1/step.yml

go-test 1.0.1

---

steps/github-release/0.9.2/step.yml

github-release 0.9.2

---

steps/xamarin-user-management/step-info.yml

deprecate xamarin user management step

---

steps/feature-list-for-release-notes/0.0.3/step.yml

Feature list for release notes 0.0.3

---

steps/github-release/0.9.3/step.yml

github-release 0.9.3

---

steps/appetize-deploy/0.9.1/step.yml

appetize-deploy 0.9.1

---

steps/sign-apk/1.2.2/step.yml

sign-apk 1.2.2

---

steps/xcode-test/1.18.16/step.yml

xcode-test 1.18.16

---

steps/feature-list-for-release-notes/0.0.4/step.yml

feature-list-for-release-notes 0.0.4

---

steps/deploy-to-itunesconnect-application-loader/0.9.3/step.yml

deploy-to-itunesconnect-application-loader 0.9.3

---

steps/github-release-downloader/0.0.1/step.yml

github-release-downloader 0.0.1

---

steps/github-release-downloader/0.0.2/step.yml

github-release-downloader 0.0.2

---

steps/versionbox-deploy/0.0.2/step.yml

versionbox-deploy 0.0.2

---

steps/xcode-build-for-simulator/0.9.0/step.yml

xcode-build-for-simulator 0.9.0

---

steps/fastlane-match/0.2.0/step.yml

fastlane-match 0.2.0

---

steps/apispotter-test-runner/0.0.1/step.yml

apispotter-test-runner 0.0.1

---

handlers/audit/main.go
handlers/deploy/main.go
handlers/generate-specs/main.go
handlers/step-info/main.go

update release logs

---

handlers/deploy/main.go

updated slim-spec gzip compression

---

handlers/deploy/main.go

This reverts commit a1a5efc6334c0c356fd378a9e6558a0898d14745.

Revert "updated slim-spec gzip compression (#1645)"

---

steps/cocoapods-dependency-check/0.0.1/step.yml

cocoapods-dependency-check 0.0.1

---

steps/jira-comments/0.0.1/step.yml

jira-comments 0.0.1

---

steps/sonarqube-scanner/1.0.4/step.yml

sonarqube-scanner 1.0.4

---

steps/apk-info/1.4.1/step.yml

apk-info 1.4.1

---

handlers/validate/Gopkg.lock
handlers/validate/validators/valueoptions/valueoptions.go
handlers/validate/vendor/github.com/bitrise-io/go-utils/pathutil/pathutil.go

skip deprecated step.yml checks

---

steps/deploy-to-itunesconnect-shenzhen/step-info.yml

Deprecate shenzhen

---

steps/project-scanner/step-info.yml

deprecate repository scanner

---

steps/flutter/0.0.5/step.yml

flutter 0.0.5

---

steps/trigger-bitrise-workflow/0.0.5/step.yml

trigger-bitrise-workflow 0.0.5

---

steps/jira-comments/0.0.1/step.yml

Jira comments 0.0.1

---

steps/openstf-connect/0.0.6/step.yml

openstf-connect 0.0.6

---

steps/trigger-bitrise-workflow/0.0.6/step.yml

trigger-bitrise-workflow 0.0.6

---

steps/jira-comments/0.0.2/step.yml

jira-comments 0.0.2

---

handlers/validate/Gopkg.lock
handlers/validate/main.go
handlers/validate/steplib/step.go
handlers/validate/steplib/steplib.go
handlers/validate/steplib/version.go
handlers/validate/validators/collection/collection.go
handlers/validate/validators/typetags/typetags.go
handlers/validate/validators/valueoptions/valueoptions.go
handlers/validate/vendor/github.com/bitrise-io/envman/LICENSE
handlers/validate/vendor/github.com/bitrise-io/envman/models/models.go
handlers/validate/vendor/github.com/bitrise-io/envman/models/models_methods.go
handlers/validate/vendor/github.com/bitrise-io/go-utils/command/command.go
handlers/validate/vendor/github.com/bitrise-io/go-utils/command/file.go
handlers/validate/vendor/github.com/bitrise-io/go-utils/command/zip.go
handlers/validate/vendor/github.com/bitrise-io/go-utils/errorutil/errorutil.go
handlers/validate/vendor/github.com/bitrise-io/go-utils/fileutil/fileutil.go
handlers/validate/vendor/github.com/bitrise-io/go-utils/sliceutil/sliceutil.go
handlers/validate/vendor/github.com/bitrise-io/stepman/LICENSE
handlers/validate/vendor/github.com/bitrise-io/stepman/_tests/integration/test-step/LICENSE
handlers/validate/vendor/github.com/bitrise-io/stepman/models/models.go
handlers/validate/vendor/github.com/bitrise-io/stepman/models/models_methods.go

revision + 2 new handlers added

---

steps/jira-comments/0.0.3/step.yml

jira-comments 0.0.3

---

steps/update-jira-issue-field/1.0.2/step.yml

update-jira-issue-field 1.0.2

---

steps/jira-comments/0.0.4/step.yml

jira-comments 0.0.4

---

steps/apk-info/1.4.2/step.yml

apk-info 1.4.2

---

steps/stamp-appicon-with-version-number/1.1.0/step.yml

- [ x ] __I will not move an already shared step version's tag to another commit__
- [ x ] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [ x ] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [ x ] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [ x ] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)
Updated the step with customisations for foreground …

stamp-appicon-with-version-number 1.1.0

---

steps/deploygate--upload-app-bitrise-step/1.0.1/step.yml

deploygate--upload-app-bitrise-step 1.0.1

---

steps/bitrise-to-appscan/0.2.4/step.yml

- [*] __I will not move an already shared step version's tag to another commit__
- [*] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [*] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [*] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [*] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

bitrise-to-appscan 0.2.4

---

steps/flutter/0.0.6/step.yml

flutter 0.0.6

---

steps/cordova-archive/1.2.0/step.yml

cordova-archive 1.2.0

---

steps/telegram-notify/1.0.2/step.yml

telegram-notify 1.0.2

---

steps/comment-on-github-pull-request/0.9.0/step.yml

comment-on-github-pull-request 0.9.0

---

steps/flutter/0.0.7/step.yml

flutter 0.0.7

---

steps/comment-on-github-pull-request/0.9.1/step.yml

comment-on-github-pull-request 0.9.1

---

steps/zip-directory-and-export-its-path/1.0.2/step.yml

zip-directory-and-export-its-path 1.0.2

---

steps/openstf-connect/0.0.7/step.yml

openstf-connect 0.0.7

---

steps/open-vpn/0.0.2/step.yml

open-vpn 0.0.2

---

steps/flutter-installer/assets/icon.svg

Flutter Installer: step icon added

---

steps/flutter-build/assets/icon.svg
steps/flutter-test/assets/icon.svg

added flutter-test and flutter-build icons

---

steps/comment-on-github-pull-request/0.9.2/step.yml

comment-on-github-pull-request 0.9.2

---

steps/bitrise-step-version-pre-release-info/1.0.3/step.yml

bitrise-step-version-pre-release-info 1.0.3

---

steps/send-microsoft-teams-message/0.1.0/step.yml

send-microsoft-teams-message 0.1.0

---

handlers/validate/main.go
handlers/validate/steplib/steplib.go
handlers/validate/steplib/version.go
handlers/validate/validators/changed-stepid/changed-stepid.go

If check runs for a step:
or for the whole StepLib:

added validator for checking duplicated step IDs

---

steps/sonarqube-msbuild-scanner/1.0.0/step.yml

sonarqube-msbuild-scanner 1.0.0

---

steps/bundle-universal-apk/0.0.2/step.yml

bundle-universal-apk 0.0.2

---

steps/bundle-universal-apk/0.0.3/step.yml
steps/bundle-universal-apk/assets/icon.svg

Bundle universal apk 0.0.3

---

steps/android-detekt/0.0.2/step.yml

android-detekt 0.0.2

---

steps/export-ios-to-lingohub/0.0.1/step.yml

export-ios-to-lingohub 0.0.1

---

steps/export-lingohub-to-ios/0.0.1/step.yml

Export lingohub to ios 0.0.1

---

steps/telegram-notify/1.0.5/step.yml

telegram-notify 1.0.5

---

steps/export-ios-to-lingohub/0.0.2/step.yml

export-ios-to-lingohub 0.0.2

---

steps/export-lingohub-to-ios/0.0.2/step.yml

export-lingohub-to-ios 0.0.2

---

steps/comment-on-github-pull-request/0.9.3/step.yml

comment-on-github-pull-request 0.9.3

---

steps/export-lingohub-to-ios/0.0.3/step.yml

export-lingohub-to-ios 0.0.3

---

steps/xcode-test-bundle-builder/0.0.7/step.yml

- [x ] __I will not move an already shared step version's tag to another commit__
- [ x] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [x ] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [x ] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [x ] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

xcode-test-bundle-builder 0.0.7

---

steps/bundle-universal-apk/0.0.4/step.yml
steps/bundle-universal-apk/assets/icon.svg

Bundle universal apk 0.0.4

---

steps/theappspajamas-service-account-key-installer/0.0.3/step.yml

- [yes ] __I will not move an already shared step version's tag to another commit__
- [ yes] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [ yes] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [ yes] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [ yes] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

TheAppsPajamas service-account-key-installer 0.0.3

---

steps/bundle-universal-apk/0.0.5/step.yml
steps/bundle-universal-apk/assets/icon.svg

Bundle universal apk 0.0.5

---

steps/swift-package-manager-test-for-mac/0.0.1/step.yml

swift-package-manager-test-for-mac 0.0.1

---

steps/swift-package-manager-build-for-mac/0.0.1/step.yml

swift-package-manager-build-for-mac 0.0.1

---

steps/swift-package-manager-xcodeproj-for-mac/0.0.1/step.yml

swift-package-manager-xcodeproj-for-mac 0.0.1

---

steps/generate-text-file/0.1.0/step.yml

https://github.com/bitrise-community/bitrise-step-generate-text-file/releases/0.1.0

generate-text-file 0.1.0

---

steps/apk-info/1.4.4/step.yml

apk-info 1.4.4

---

steps/swift-environment-variable-injector/0.1.1/step.yml

swift-environment-variable-injector 0.1.1

---

steps/trigger-bitrise-workflow/0.0.7/step.yml

trigger-bitrise-workflow 0.0.7

---

steps/sonarqube-scanner/1.0.6/step.yml

sonarqube-scanner 1.0.6

---

steps/ascii-generator/1.0.4/step.yml

https://github.com/bitrise-steplib/bitrise-step-ascii-art-generator/releases/1.0.4

ascii-generator 1.0.4

---

steps/xctest-html-report/0.1.3/step.yml

xctest-html-report 0.1.3

---

steps/applivery-ios/0.3.0/step.yml

applivery-ios 0.3.0

---

steps/applivery-android/0.3.0/step.yml

applivery-android 0.3.0

---

steps/giphy/0.2.0/step.yml

giphy 0.2.0

---

steps/recursive-touch/step-info.yml

deprecate recursive-touch

---

steps/applivery-android/0.3.1/step.yml

- Fixed deployment values vars
- Fixed step description and links as reported by @koral-- 

applivery-android 0.3.1

---

steps/applivery-ios/0.3.1/step.yml

- Conditionally upload Certificates and Provisioning Profiles by checking a new param called `uploadCodeSigning `
- Prepared to support uploading of `.app` but yet ready.
- Updated Step name (title)

applivery-ios 0.3.1

---

steps/applivery-android/0.3.2/step.yml

- Just updating Step Name (title)

applivery-android 0.3.2

---

steps/jandi-message/0.1.0/step.yml

jandi-message 0.1.0

---

steps/appcenter-app-release/1.0.0/step.yml

appcenter-app-release 1.0.0

---

steps/bitrise-step-version-pre-release-info/1.1.0/step.yml

- [*] __I will not move an already shared step version's tag to another commit__
- [*] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [*] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [*] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [*] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

bitrise-step-version-pre-release-info 1.1.0

---

steps/appcenter-ipa-upload/0.0.2/step.yml

appcenter-ipa-upload 0.0.2

---

steps/get-app/0.1.0/step.yml

I cannot use git via http because I have 2FA active on my account, and I prefer ssh over https for git, because of which the last step failed

Add get-app

---

steps/steps-chatwork-message/0.0.1/step.yml

chatwork-message-0.0.1

---

steps/appcenter-apk-upload/0.0.1/step.yml

I'll participate in `Bitrise User Group Meetup #1` which will be held in Japan on July 30.
Thank you as always!

appcenter-apk-upload 0.0.1

---

steps/loco/0.0.3/step.yml

loco 0.0.3

---

steps/git-tag-project-version-and-build-number/1.0.3/step.yml

git-tag-project-version-and-build-number 1.0.3

---

steps/generate-image-difference/0.0.2/step.yml

generate-image-difference 0.0.2

---

steps/get-npm-package-version/1.0.1/step.yml

- [✅] __I will not move an already shared step version's tag to another commit__
- [✅] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [✅] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [✅] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [✅] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)
I have fixed the typos in the step description and README, per …

get-npm-package-version 1.0.1

---

steps/set-gem-home/0.0.1/step.yml

set-gem-home 0.0.1

---

steps/bundler/0.0.1/step.yml

bundler 0.0.1

---

steps/xcodebuild/0.0.1/step.yml

xcodebuild 0.0.1

---

steps/bitrise-step-install-bundler/1.1.2/step.yml

bitrise-step-install-bundler 1.1.2

---

steps/bitrise-step-appledoc/1.0.2/step.yml

bitrise-step-appledoc 1.0.2

---

steps/bitrise-step-icon-overlay/1.0.1/step.yml

bitrise-step-icon-overlay 1.0.1

---

steps/xcodebuild/0.0.2/step.yml

xcodebuild 0.0.2

---

steps/set-macos-timezone/0.0.1/step.yml

set-macos-timezone 0.0.1

---

steps/xcuitestbrowserstack/1.0.1/step.yml

- [Yes] __I will not move an already shared step version's tag to another commit__
- [Yes] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [Yes] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [Yes] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [Yes] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

xcuitestbrowserstack 1.0.1

---

steps/set-macos-timezone/0.0.1/step.yml
steps/set-macos-timezone/0.0.2/step.yml

set-macos-timezone 0.0.2

---

steps/xcuitestbrowserstack/1.0.2/step.yml

- [Yes ] __I will not move an already shared step version's tag to another commit__
- [Yes ] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [ Yes] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [Yes] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [Yes ] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

xcuitestbrowserstack 1.0.2

---

steps/set-macos-timezone/0.0.3/step.yml

set-macos-timezone 0.0.3

---

steps/xcodebuild/0.0.3/step.yml

xcodebuild 0.0.3

---

steps/bundler/0.0.2/step.yml

bundler 0.0.2

---

steps/bundler/0.0.3/step.yml

bundler 0.0.3

---

steps/xcuitestbrowserstack/1.0.5/step.yml

- [Yes ] __I will not move an already shared step version's tag to another commit__
- [Yes] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [Yes ] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [Yes ] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [Yes ] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

xcuitestbrowserstack 1.0.5

---

steps/bundler/0.0.4/step.yml

bundler 0.0.4

---

steps/set-macos-timezone/0.0.4/step.yml

set-macos-timezone 0.0.4

---

.gitignore
steps/ios-auto-provision/1.3.2/step.yml

https://github.com/bitrise-steplib/steps-ios-auto-provision/releases/1.3.2

ios-auto-provision 1.3.2

---

steps/firebase-app-distribution/0.1.0/step.yml

firebase-app-distribution 0.1.0

---

steps/nuget-restore/1.1.0/step.yml

https://github.com/bitrise-steplib/steps-nuget-restore/releases/1.1.0

nuget-restore 1.1.0

---

steps/xcode-archive/2.6.1/step.yml

https://github.com/bitrise-steplib/steps-xcode-archive/releases/2.6.1

xcode-archive 2.6.1

---

steps/firebase-dsym-upload/1.0.0/step.yml

firebase-dsym-upload 1.0.0

---

steps/firebase-app-distribution/0.2.0/step.yml

firebase-app-distribution 0.2.0

---

steps/firebase-app-distribution/0.3.0/step.yml
steps/firebase-app-distribution/assets/icon.svg

----
**Changelog:** 
- Check against misconfig. 
- Fix Support URL. 
- Flutter support
- Icon added (this time correct)

Firebase app distribution 0.3.0

---

steps/steps-chatwork-message/0.0.3/step.yml

steps-chatwork-message 0.0.3

---

steps/discord-message/0.0.1/step.yml

Discord message 0.0.1

---

steps/xcuitestbrowserstack/1.0.6/step.yml

- [YES] __I will not move an already shared step version's tag to another commit__
- [YES ] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [YES ] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [YES ] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [YES ] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

xcuitestbrowserstack 1.0.6

---

steps/pagerduty/assets/icon.svg

add icon for pagerduty step

---

steps/git-tag-project-version-and-build-number/1.0.4/step.yml

git-tag-project-version-and-build-number 1.0.4

---

steps/trigger-bitrise-workflow/0.0.8/step.yml

trigger-bitrise-workflow 0.0.8

---

steps/bundle-universal-apk/0.0.6/step.yml
steps/bundle-universal-apk/assets/icon.svg

Bundle universal apk 0.0.6

---

steps/xcodegen/0.0.5/step.yml

xcodegen 0.0.5

---

steps/bluepill-build-test-for-ios/0.3.0/step.yml

bluepill-build-test-for-ios 0.3.0

---

steps/flutter/0.0.8/step.yml

flutter 0.0.8

---

steps/unzip/0.0.3/step.yml

unzip 0.0.3

---

steps/loco/0.1.1/step.yml

loco 0.1.1

---

steps/tryoutapps-shaman/1.0.1/step.yml

tryoutapps-shaman 1.0.1

---

steps/firebase-app-distribution/0.4.0/step.yml

firebase-app-distribution 0.4.0

---

steps/get-pubspec-version-and-build-number/1.0.0/step.yml

- [ x ] __I will not move an already shared step version's tag to another commit__
- [ x ] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [ x ] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [ x ] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [ x ] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

get-pubspec-version-and-build-number 1.0.0

---

steps/firebase-app-distribution/0.5.0/step.yml

firebase-app-distribution 0.5.0

---

steps/xctest-html-report/0.2.0/step.yml

---
https://github.com/BirmacherAkos/bitrise-step-xctest-html-report/releases/tag/0.2.0

xctest-html-report 0.2.0

---

steps/xcuitestbrowserstack/1.0.8/step.yml

- [YES] __I will not move an already shared step version's tag to another commit__
- [YES ] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [YES ] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [YES ] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [YES] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

xcuitestbrowserstack 1.0.8

---

steps/xctest-html-report/0.2.1/step.yml

xctest-html-report 0.2.1

---

steps/firebase-dsym-upload/1.0.1/step.yml

This PR fixes an issue where spaces in directory names could cause the upload to fail.

firebase-dsym-upload 1.0.1

---

steps/git-tag-project-version-and-build-number/1.0.5/step.yml

git-tag-project-version-and-build-number 1.0.5

---

steps/bluepill-build-test-for-ios/0.4.0/step.yml

Bluepill build test for ios 0.4.0

---

steps/release-notes-extractor/0.0.1/step.yml

release-notes-extractor 0.0.1

---

steps/flutter/0.0.9/step.yml

flutter 0.0.9

---

steps/code-signing-setting-patch/1.0.4/step.yml

code-signing-setting-patch 1.0.4

---

steps/genymotion-cloud-saas-start/0.0.1/step.yml

genymotion-cloud-saas-start 0.0.1

---

steps/genymotion-cloud-saas-stop/0.0.2/step.yml

genymotion-cloud-saas-stop 0.0.2

---

steps/git-tag-project-version-and-build-number/1.0.6/step.yml

git-tag-project-version-and-build-number 1.0.6

---

steps/release-notes-extractor/0.1.0/step.yml

release-notes-extractor 0.1.0

---

steps/steps-chatwork-message/0.0.4/step.yml

steps-chatwork-message 0.0.4

---

steps/release-notes-extractor/0.1.1/step.yml

release-notes-extractor 0.1.1

---

steps/get-pubspec-version-and-build-number/1.0.2/step.yml

get-pubspec-version-and-build-number 1.0.2

---

steps/genymotion-cloud-saas-start/assets/icon.svg
steps/genymotion-cloud-saas-stop/assets/icon.svg

Add SVG icons for genymotion-cloud steps

---

steps/bitbucket-server-post-build-status/0.0.8/step.yml

Bitbucket server post build status 0.0.3

---

steps/app-gallery-deploy/1.0.0/step.yml

app-gallery-deploy 1.0.0

---

steps/loco/0.1.3/step.yml

loco 0.1.3

---

steps/deploygate--upload-app-bitrise-step/1.1.0/step.yml

Hi, bitrise team 😃 Could you please check and merge this PR? Thanks.

New release for DeployGate/upload-app-bitrise-step to 1.1.0

---

handlers/validate/main.go

removed collection check

---

handlers/validate/main.go
handlers/validate/validators/collection/collection.go
handlers/validate/vendor/github.com/hashicorp/go-version/go.mod

added newest cli version limiter

---

steps/magicpod-ui-test/0.47.0/step.yml

magicpod-ui-test 0.47.0

---

steps/jira-issue-status-update/0.1.0/step.yml

jira-issue-status-update 0.1.0

---

steps/firebase-app-distribution/0.6.0/step.yml

firebase-app-distribution 0.6.0

---

handlers/validate/validators/collection/collection.go
handlers/validate/validators/collection/collection_test.go

updated version check for cli

---

bitrise.yml
handlers/algolia-deploy/step.sh
handlers/algolia-deploy/step.yml

add algolia deploy step to the deploy workflow

---

steps/firebase-dsym-upload/1.0.2/step.yml

Fixes issue where a dsym path that has spaces in it would cause an error

firebase-dsym-upload 1.0.2

---

steps/jira-issue-status-update/0.1.2/step.yml

jira-issue-status-update 0.1.2

---

steps/magicpod-ui-test/0.47.1/step.yml

magicpod-ui-test 0.47.1

---

steps/update-xcode-project-provisioning/1.0.0/step.yml

update-xcode-project-provisioning 1.0.0

---

steps/zipalign-apk/0.2.0/step.yml

zipalign-apk 0.2.0

---

steps/azure-devops-status/1.0.0/step.yml

azure-devops-status 1.0.0

---

steps/azure-devops-status/1.0.1/step.yml
steps/azure-devops-status/assets/icon.svg

azure-devops-status 1.0.1

---

steps/applivery-android/0.3.3/step.yml

Support for [Android App Bundle](https://www.applivery.com/docs/advanced/android-app-bundle/)

applivery-android 0.3.3

---

steps/update-xcode-project-provisioning/1.1.0/step.yml

update-xcode-project-provisioning 1.1.0

---

steps/android-detekt/0.0.3/step.yml

android-detekt 0.0.3

---

steps/create-apple-documentation/1.1.0/step.yml

This PR releases a new version of the step, publishing a fix for a [bug reported](https://github.com/FutureWorkshops/bitrise-step-create-apple-documentation/issues/1).

Update create-apple-documentation to fix reported issue

---

handlers/validate/validators/collection/collection.go
slim_spec_schema.json
spec_schema.json

added checks

---

steps/firebase-app-distribution/0.7.0/step.yml

firebase-app-distribution 0.7.0

---

steps/apk-info/1.4.5/step.yml

apk-info 1.4.5

---

steps/git-tag-project-version-and-build-number/1.0.7/step.yml

git-tag-project-version-and-build-number 1.0.7

---

steps/xcode-project-info/2.1.0/step.yml

xcode-project-info 2.1.0

---

PULL_REQUEST_TEMPLATE.md

Updated template

---

steps/swiftlint/0.6.0/step.yml

swiftlint 0.6.0

---

steps/swiftlint/0.7.0/step.yml

swiftlint 0.7.0

---

steps/xcuitestbrowserstack/1.0.9/step.yml

- [Yes ] __I will not move an already shared step version's tag to another commit__
- [Yes ] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [Yes ] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [ Yes] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [Yes ] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

xcuitestbrowserstack 1.0.9

---

steps/appcenter-ipa-upload/0.0.3/step.yml

Added ability to enter comments when uploading an IPA file from Bitrise to AppCenter.
I've included detailed instructions on how to use it in Readme.md.

appcenter-ipa-upload 0.0.3

---

steps/get-flutter-version/0.0.1/step.yml

Following up on https://github.com/bitrise-io/bitrise-steplib/pull/2494
**New Step**

Get flutter version 0.0.1

---

steps/sonarqube-scanner/1.0.7/step.yml

sonarqube-scanner 1.0.7

---

steps/firebase-dsym-upload/1.1.1/step.yml

Fixes an issue where the step may fail for some users.

firebase-dsym-upload 1.1.1

---

steps/swiftlint-extended/step-info.yml

Adding swiftlint-extended step metadata.

---

steps/bitrise-step-ionic-build/0.0.1/step.yml
steps/bitrise-step-ionic-build/step-info.yml

bitrise-step-ionic-build 0.0.1

---

steps/applivery-android/0.3.4/step.yml

applivery-android 0.3.4

---

steps/applivery-ios/0.3.2/step.yml

applivery-ios 0.3.2

---

steps/xcuitestbrowserstack/1.0.13/step.yml

- [ yes] __I will not move an already shared step version's tag to another commit__
- [ yes ] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [ yes] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository) …

xcuitestbrowserstack 1.0.13

---

steps/genymotion-cloud-saas-stop/0.1.2/step.yml

genymotion-cloud-saas-stop 0.1.2

---

steps/genymotion-cloud-saas-start/0.1.2/step.yml

genymotion-cloud-saas-start 0.1.2

---

steps/genymotion-cloud-saas-start/step-info.yml
steps/genymotion-cloud-saas-stop/step-info.yml

Marking steps as verified

---

steps/flutter/0.0.10/step.yml

flutter 0.0.10

---

steps/genymotion-cloud-saas-start/0.1.3/step.yml

genymotion-cloud-saas-start 0.1.3

---

steps/find-jira-issue/step-info.yml

Adding step metadata

---

steps/genymotion-cloud-saas-start/0.1.4/step.yml

genymotion-cloud-saas-start 0.1.4

---

steps/app-gallery-deploy/1.0.1/step.yml

app-gallery-deploy 1.0.1

---

steps/pagerduty/step-info.yml

[PLATFORM-198] Marking Pagerduty verified

---

steps/aws-device-farm-runner/0.0.8/step.yml

aws-device-farm-runner 0.0.8

---

steps/app-gallery-deploy/1.1.0/step.yml

app-gallery-deploy 1.1.0

---

steps/perfecto-upload/step-info.yml

perfecto-upload: verified

---

steps/deploygate--upload-app-bitrise-step/1.1.1/step.yml

deploygate--upload-app-bitrise-step 1.1.1

---

steps/deploygate--upload-app-bitrise-step/step-info.yml

deploygate--upload-app-bitrise-step step verified

---

steps/jira-comments/0.0.5/step.yml

jira-comments 0.0.5

---

steps/sonarqube-quality-gate/step-info.yml

Adding metadata to sonarquebe-quality-gate

---

steps/genymotion-cloud-saas-start/0.1.5/step.yml

genymotion-cloud-saas-start 0.1.5

---

steps/comment-on-github-pull-request/0.9.4/step.yml

comment-on-github-pull-request 0.9.4

---

steps/sentry-dsym-upload/step-info.yml

sentry-dsym-upload maintainer update

---

steps/codecov/2.0.0/step.yml

codecov 2.0.0

---

steps/xctest-html-report/1.0.0/step.yml

xctest-html-report 1.0.0

---

steps/xcuitestbrowserstack/1.0.15/step.yml

URGENT - xcuitestbrowserstack 1.0.15

---

steps/firebase-app-distribution/0.8.0/step.yml

firebase-app-distribution 0.8.0

---

steps/xcuitestbrowserstack/1.0.16/step.yml

- [yes] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [yes] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository) …

xcuitestbrowserstack 1.0.16

---

steps/openstf-connect/0.0.8/step.yml

openstf-connect 0.0.8

---

steps/s3-download/1.0.0/step.yml
steps/s3-download/step-info.yml

Original PR: #2703 
- No longer setting project_type_target
- Fixing the type_tags

Step that can be used to download resources from AWS S3

---

steps/xcuitestbrowserstack/1.0.17/step.yml

- [yes] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [yes] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository) …

xcuitestbrowserstack 1.0.17

---

steps/add-trace-sdk/1.1.0/step.yml

add-trace-sdk 1.1.0

---

steps/open-vpn/step-info.yml

Change open-vpn step maintainer to bitrise

---

steps/add-trace-sdk/1.1.1/step.yml

add-trace-sdk 1.1.1

---

steps/xcuitestbrowserstack/2.0.0/step.yml

- [ yes] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [ yes] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [yes ] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step …

xcuitestbrowserstack 2.0.0

---

steps/jira-comments/0.0.6/step.yml

jira-comments 0.0.6

---

steps/jira-issue-field-add-or-update/step-info.yml

Fixes the jira-issue-field-add-or-update issue with `step_info.yml`
https://github.com/bitrise-io/bitrise-steplib/pull/2727

Fix jira-issue-field-add-or-update step step_info.yml issue

---

steps/jira-issue-field-add-or-update/0.0.2/step.yml

jira-issue-field-add-or-update 0.0.2

---

steps/aws-secrets-manager/0.0.2/step.yml
steps/aws-secrets-manager/step-info.yml

aws-secrets-manager 0.0.2

---

steps/add-trace-sdk/1.2.1/step.yml

add-trace-sdk 1.2.1

---

steps/install-dotnetcore/step-info.yml

[PLAT-690]: Deprecate Install .NET Core Step

---

steps/localazy/1.0.0/step.yml
steps/localazy/step-info.yml

localazy 1.0.0

---

steps/localazy/step-info.yml

[PLAT-867] Make localazy step verified

---

steps/appgallery-deploy/0.9.0/step.yml
steps/appgallery-deploy/step-info.yml

- [yes] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [yes] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository) …

AppGallery Deploy Verified Step

---

steps/appgallery-deploy/step-info.yml

Enable the Verified Step Badge for the Deploy to Huawei App Gallery Step

Make the Huawei App Gallery Deploy step verified

---

steps/xcuitestbrowserstack/2.0.1/step.yml

- [Yes] __I will not move an already shared step version's tag to another commit__
- [Yes] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [Yes] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [Yes] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step …

xcuitestbrowserstack 2.0.1

---

steps/app-ray-mobile-security/step-info.yml

Create app-ray-mobile-security step-info.yml

---

steps/mobile-quality/1.0.2/step.yml
steps/mobile-quality/step-info.yml

mobile-quality 1.0.2

---

steps/get-info-on-android-app-bundle/0.0.1/step.yml
steps/get-info-on-android-app-bundle/step-info.yml

- ![image](https://user-images.githubusercontent.com/10161894/105122660-fc4ac280-5b19-11eb-9ce0-f80d310d1aa8.png)
- ![image](https://user-images.githubusercontent.com/10161894/105122723-15ec0a00-5b1a-11eb-9239-5df2b69681ed.png)
**New Step**

get-info-on-android-app-bundle 0.0.1

---

steps/appgallery-deploy/1.0.0/step.yml

appgallery-deploy 1.0.0

---

steps/app-ray-mobile-security/step-info.yml

[PLAT-1117] Set app-ray-mobile-security verified

---

steps/mobile-quality/step-info.yml

Mobile quality - deprecated step

---

steps/microsoft-teams-integration/1.2.0/step.yml

microsoft-teams-integration 1.2.0

---

steps/applivery-android/1.0.0/step.yml

applivery-android 1.0.0

---

steps/applivery-ios/1.0.0/step.yml

applivery-ios 1.0.0

---

steps/apps-decompiler/1.0.2/step.yml
steps/cache-push/2.5.0/step.yml
steps/install-flutter-version-manager/step-info.yml
steps/ios-auto-provision-appstoreconnect/1.0.0/step.yml

Reopened with changes from https://github.com/bitrise-io/bitrise-steplib/pull/2878 (new step, adding step-info.yml)
**New Step**

Install flutter version manager 1.0.2

---

steps/appgallery-deploy/1.5.0/step.yml

New Release: appgallery-deploy 1.5.0

---

steps/appgallery-deploy/1.5.1/step.yml

appgallery-deploy 1.5.1

---

steps/microsoft-teams-integration/1.2.2/step.yml

microsoft-teams-integration 1.2.2

---

steps/appgallery-deploy/1.5.2/step.yml

appgallery-deploy 1.5.2 (Shell Script loop issue fixed)

---

steps/beat-android-code-stats/step-info.yml

[NOJIRA] adding step-info.yml for beat-android-code-stats

---

steps/beat-android-code-stats/0.0.2/step.yml

beat-android-code-stats 0.0.2

---

steps/appgallery-deploy/1.5.3/step.yml

appgallery-deploy 1.5.3 

---

steps/microsoft-teams-integration/2.0.0/step.yml

microsoft-teams-integration 2.0.0

---

steps/veracode-security/1.0.3/step.yml

veracode-security 1.0.3

---

steps/steps-app-gallery-reports/0.9.0/step.yml
steps/steps-app-gallery-reports/step-info.yml

steps-app-gallery-reports 0.9.0

---

steps/steps-app-gallery-reports/step-info.yml

[PLAT-1517] feat(app-gallery-reports): make it a verified step

---

steps/firebase-change-file-by-env/0.0.2/step.yml
steps/firebase-change-file-by-env/step-info.yml

firebase-change-file-by-env 0.0.2

---

steps/testingbot-upload-app/step-info.yml

Fix testingbot-upload-app release

---

steps/testingbot-upload-app/0.0.1/step.yml

This is a step to upload apk/ipa files to TestingBot for Automated Mobile App Testing.
**New Step**

testingbot-upload-app 0.0.1

---

steps/s3-download/1.1.0/step.yml

Version 1.1.0 fixes an issue with the output of the step. Before, the output was not properly registered. This also includes new tests to ensure that the step runs as expected.

s3-download 1.1.0

---

steps/appaloosa/1.4.0/step.yml

Appaloosa 1.4.0 - Remove Account Creation

---

steps/data-theorem-mobile-secure/step-info.yml

Related Jira ticket
https://bitrise.atlassian.net/browse/PLAT-1703

Changing Data Theorem Mobile Secure step to verified one

---

steps/appaloosa/step-info.yml

Related Jira ticket 
https://bitrise.atlassian.net/browse/PLAT-1711

Changing Publish to Appaloosa Store step to verified one

---

steps/codecov/2.0.2/step.yml

codecov 2.0.2

---

steps/dexprotector/step-info.yml

Related ticket
https://bitrise.atlassian.net/browse/PLAT-1789

Make DexProtector step verified

---

steps/microsoft-teams-integration/2.1.1/step.yml

microsoft-teams-integration 2.1.1

---

steps/veracode-security/1.0.4/step.yml

veracode-security 1.0.4

---

steps/smart-qa/0.0.2/step.yml

smart-qa 0.0.2

---

steps/apk-info/1.4.6/step.yml

Apk info 1.4.6

---

steps/pcloudy-app-upload/step-info.yml

Add step-info.yml to pcloudy-app-upload.

Add step-info.yml to pcloudy-app-upload.

---

steps/appaloosa/1.5.0/step.yml

appaloosa-1.5.0

---

steps/firebase-app-distribution/0.9.0/step.yml

firebase-app-distribution 0.9.0

---

steps/firebase-app-distribution/0.9.1/step.yml

firebase-app-distribution 0.9.1

---

steps/aws-secrets-manager/1.0.0/step.yml

aws-secrets-manager 1.0.0

---

steps/sofy-upload/step-info.yml

[Internal ticket](https://bitrise.atlassian.net/browse/STEP-1265)

sofy upload verified

---

steps/aws-secrets-manager/2.0.0/step.yml

aws-secrets-manager 2.0.0

---

steps/jira-comments/0.0.7/step.yml

jira-comments 0.0.7

---

steps/appgallery-deploy/1.5.4/step.yml

appgallery-deploy 1.5.4

---

steps/appgallery-deploy/1.5.5/step.yml

appgallery-deploy 1.5.5

---

steps/mussel/1.0.0/step.yml
steps/mussel/step-info.yml

mussel 1.0.0

---

steps/codecov/3.0.0/step.yml

codecov 3.0.0

---

steps/mussel/step-info.yml

[Related internal ticket](https://bitrise.atlassian.net/browse/STEP-1239)

Update Musser to verified

---

steps/appium-server/0.0.2/step.yml
steps/appium-server/step-info.yml

appium-server 0.0.2

---

steps/sonarqube-scanner/1.0.8/step.yml

sonarqube-scanner 1.0.8

---

steps/sonarqube-scanner/1.0.9/step.yml

sonarqube-scanner 1.0.9

---

steps/appium-server/0.0.4/step.yml
steps/appium-server/step-info.yml

appium-server 0.0.4

---

steps/codecov/3.0.1/step.yml

codecov 3.0.1

---

steps/codecov/3.1.0/step.yml

codecov 3.1.0

---

steps/fortify-on-demand-mobile-assessment/0.0.1/step.yml
steps/fortify-on-demand-mobile-assessment/step-info.yml

Fortify on demand mobile assessment 0.0.1

---

steps/codecov/3.1.1/step.yml

codecov 3.1.1

---

steps/nuget-restore/step-info.yml
steps/xamarin-android-test/step-info.yml
steps/xamarin-archive/step-info.yml
steps/xamarin-components-restore/step-info.yml
steps/xamarin-ios-test/step-info.yml

Modify the Xamarin steps deprecation date to end of January.

[MOB-222] Update Xamarin deprecation date

---

steps/create-a-new-release-in-jira/1.0.2/step.yml

create-a-new-release-in-jira 1.0.2

---

steps/kobiton-app-upload/step-info.yml

- [-] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [-] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)

Added kobiton-app-upload step info

---

steps/kobiton-app-upload/1.0.0/step.yml

kobiton-app-upload 1.0.0

---

steps/autify-upload/0.0.2/step.yml

Autify upload 0.0.2

---

steps/flutter/0.1.0/step.yml

flutter 0.1.0

---

steps/kobiton-execute-test/step-info.yml

Added kobiton-execute-test step-info.yml

---

steps/tuist/step-info.yml

Make Tuist step verified

---

steps/google-play-rollout-update/0.0.2/step.yml
steps/google-play-rollout-update/step-info.yml

google-play-rollout-update 0.0.2

---

steps/comment-on-github-pull-request/0.10.1/step.yml

comment-on-github-pull-request 0.10.1

---

steps/scan-with-appsweep/1.0.0/step.yml
steps/scan-with-appsweep/assets/icon.svg
steps/scan-with-appsweep/step-info.yml

scan-with-appsweep 1.0.0

---

steps/comment-on-github-pull-request/0.11.0/step.yml

comment-on-github-pull-request 0.11.0

---

steps/scan-with-appsweep/step-info.yml

- CLA Signed ✅ 
- Step has an icon ✅

Make Scan with AppSweep step verified

---

steps/firebase-app-distribution/0.10.0/step.yml

firebase-app-distribution 0.10.0

---

steps/run-eas-build/0.1.0/step.yml
steps/run-eas-build/step-info.yml

https://github.com/bitrise-steplib/bitrise-step-run-eas-build/releases/0.1.0
- This repo uses `bitrise run check` and `bitrise run e2e` commands for testing
- I was running `bitrise stepman audit --step-yml ./step.yml`
**New Step**

run-eas-build 0.1.0

---

steps/codecov/3.1.3/step.yml

codecov 3.1.3

---

steps/update-gitops-repository/1.0.1/step.yml

update-gitops-repository 1.0.1

---

steps/connect-to-fortigate-sslvpn/1.0.0/step.yml
steps/connect-to-fortigate-sslvpn/step-info.yml

Note: the parameters I used to test are in my secrets file and are private
**New Step**

connect-to-fortigate-sslvpn 1.0.0

---

steps/configcat-feature-flag-sync/step-info.yml

We will have a new verified step and this just creates the necessary info yaml file for it.

Add configcat info yaml

---

steps/flutter/0.1.2/step.yml

flutter 0.1.2

---

steps/bitbucket-server-post-build-status/0.0.13/step.yml

bitbucket-server-post-build-status 0.0.13

---

steps/start-xcode-simulator/step-info.yml

Create step-info.yml for start-xcode-simulator

---

steps/get-flutter-version/0.0.2/step.yml
steps/get-flutter-version/step-info.yml

get-flutter-version 0.0.2

---

steps/snyk/0.1.0/step.yml

This is a follow-up on https://github.com/bitrise-io/bitrise-steplib/pull/3586
- [X ] __I will not move an already shared step version's tag to another commit__
- [X ] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [X ] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [X ] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this …

Bitrise Step - Snyk

---

steps/set-pubspec-application-version/0.0.2/step.yml
steps/set-pubspec-application-version/step-info.yml

set-pubspec-application-version 0.0.2

---

steps/set-pubspec-application-version/0.0.3/step.yml
steps/set-pubspec-application-version/step-info.yml

set-pubspec-application-version 0.0.3

---

steps/autify-upload/0.0.3/step.yml
steps/snyk/1.0.0/step.yml

This is the initial version of the Snyk step with an html output optionally generated and deployed as artifact.
- [x ] __I will not move an already shared step version's tag to another commit__
- [x ] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [x ] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [x ] I did run `bitrise run audit-this-step` (in the step's repository …

Snyk 1.0.0

---

steps/jira-issue-update-build/0.2.3/step.yml

jira-issue-update-build 0.2.3

---

steps/rustup-install/0.2.0/step.yml

rustup-install 0.2.0

---

steps/swift-environment-variable-injector/0.1.2/step.yml

[update] variable injector version 0.1.2

---

steps/firebase-dsym-upload/2.0.1/step.yml

firebase-dsym-upload 2.0.1

---

steps/browserstack-bitrise-xcui-step/1.0.1/step.yml
steps/browserstack-bitrise-xcui-step/step-info.yml

browserstack-bitrise-xcui-step 1.0.1

---

steps/codecov/3.2.0/step.yml

codecov 3.2.0

---

steps/repeato-test-runner/0.0.2/step.yml
steps/repeato-test-runner/step-info.yml

repeato-test-runner 0.0.2

---

steps/swift-environment-variable-injector/0.1.3/step.yml

[update] variable injector version 0.1.3

---

steps/jira-issue-update-build/0.2.5/step.yml

jira-issue-update-build 0.2.5

---

steps/bitrise-step-eschecker/0.0.1/step.yml
steps/bitrise-step-eschecker/step-info.yml

bitrise-step-eschecker 0.0.1

---

steps/nitro-ios/4.4.0/step.yml

nitro-ios 4.4.0

---

steps/nitro-android/4.4.0/step.yml

nitro-android 4.4.0

---

steps/tuist/0.2.0/step.yml
steps/tuist/0.2.1/step.yml

tuist 0.2.1

---

PULL_REQUEST_TEMPLATE.md
steps/maestro-cloud-upload/1.1.0/step.yml

maestro-cloud-upload 1.1.0

---

steps/swiftlint/0.10.1/step.yml

swiftlint 0.10.1

---

steps/genymotion-saas-install-gmsaas-cli/0.0.1/step.yml
steps/genymotion-saas-install-gmsaas-cli/step-info.yml

genymotion-saas-install-gmsaas-cli 0.0.1

---

steps/appium-server/0.0.6/step.yml

appium-server 0.0.6

---

steps/nitro-android/4.5.0/step.yml

nitro-android 4.5.0

---

steps/nitro-ios/4.5.0/step.yml

nitro-ios 4.5.0

---

steps/aws-secrets-manager/2.2.0/step.yml

aws-secrets-manager 2.2.0

---

steps/pull-intermediate-files/icon.svg

jira: https://bitrise.atlassian.net/browse/CI-621

Icon update for Pull Pipeline intermediate files

---

steps/nitro-android/4.6.0/step.yml

nitro-android 4.6.0

---

steps/snyk/1.0.2/step.yml

snyk 1.0.2

---

steps/snyk/1.0.3/step.yml

- [ x] __I will not move an already shared step version's tag to another commit__
- [x ] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [ x] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [ x] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step …

snyk 1.0.3

---

steps/configcat-feature-flag-sync/0.0.5/step.yml

configcat-feature-flag-sync 0.0.5

---

steps/jira-comments/0.0.8/step.yml

jira-comments 0.0.8

---

steps/appdome-build-2secure-android/1.0.7/step.yml

Update to existing step:
added return values

appdome-build-2secure-android 1.0.7

---

steps/telegram-notify/2.0.0/step.yml

telegram-notify 2.0.0

---

steps/create-new-app-store-release/assets/icon.svg

New shiny icon for the RA step.

Add RA Step icon

---

steps/appdome-build-2secure-android/2.0.0/step.yml

appdome-build-2secure-android 2.0.0

---

steps/codecov/3.3.0/step.yml

codecov 3.3.0

---

steps/maestro-cloud-upload/1.2.0/step.yml

maestro-cloud-upload 1.2.0

---

steps/appdome-build-2secure-android/3.0.0/step.yml

Appdome build 2secure android 3.0.0

---

steps/flutter/0.1.4/step.yml

flutter 0.1.4

---

steps/appetize-deploy/assets/icon.svg

Update Appetize Deploy Step icon to match Appetize Branding

---

steps/kobiton-execute-test/2.0.0/step.yml

kobiton-execute-test 2.0.0

---

steps/kobiton-app-upload/1.0.3/step.yml

kobiton-app-upload 1.0.3

---

steps/embrace-symbol-upload/1.0.0/step.yml
steps/embrace-symbol-upload/step-info.yml

embrace-symbol-upload 1.0.0

---

steps/appgallery-deploy/1.5.7/step.yml

appgallery-deploy 1.5.7

---

steps/sonarqube-scanner/1.0.10/step.yml

sonarqube-scanner 1.0.10

---

steps/maestro-cloud-upload/1.3.0/step.yml

maestro-cloud-upload 1.3.0

---

steps/maestro-cloud-upload/1.3.2/step.yml

maestro-cloud-upload 1.3.2

---

steps/firebase-app-distribution/0.11.0/step.yml

Firebase app distribution 0.11.0

---

steps/maestro-cloud-upload/1.4.0/step.yml

maestro-cloud-upload 1.4.0

---

steps/translized/1.0.2/step.yml
steps/translized/step-info.yml

translized 1.0.2

---

steps/scan-with-appsweep/2.0.0/step.yml

scan-with-appsweep 2.0.0

---

steps/run-tests-using-marathon-cloud/1.0.0/step.yml

run-tests-using-marathon-cloud 1.0.0

---

steps/configcat-feature-flag-sync/0.0.8/step.yml

configcat-feature-flag-sync 0.0.8

---

steps/scan-with-appsweep/2.0.2/step.yml

- Address warnings for step running locally on non-GNU machines
- Properly handle custom build variants

scan-with-appsweep 2.0.2

---

steps/restore-s3-cache/0.9.1/step.yml
steps/restore-s3-cache/step-info.yml

https://github.com/bitrise-steplib/bitrise-step-restore-s3-cache/releases/0.9.1
**New Step**

restore-s3-cache 0.9.1

---

steps/flutter/0.1.5/step.yml

flutter 0.1.5

---

steps/applivery-ios/1.0.1/step.yml

applivery-ios 1.0.1

---

steps/genymotion-saas-install-gmsaas-cli/0.0.3/step.yml

genymotion-saas-install-gmsaas-cli 0.0.3

---

steps/deploy-to-updraft/0.0.1/step.yml
steps/deploy-to-updraft/step-info.yml

deploy-to-updraft 0.0.1

---

steps/update-gitops-repository/2.0.3/step.yml

https://github.com/bitrise-io/bitrise-step-update-gitops-repository/releases/2.0.3

update-gitops-repository 2.0.3

---

steps/flutter/0.1.7/step.yml

flutter 0.1.7

---

steps/maestro-cloud-upload/1.5.0/step.yml

maestro-cloud-upload 1.5.0

---

steps/run-tests-using-marathon-cloud/1.0.1/step.yml

run-tests-using-marathon-cloud 1.0.1

---

steps/device-cloud-for-maestro/0.0.6/step.yml
steps/device-cloud-for-maestro/step-info.yml

device-cloud-for-maestro 0.0.6

---

steps/set-pubspec-application-version/0.1.0/step.yml

set-pubspec-application-version 0.1.0

---

steps/device-cloud-for-maestro/0.0.7/step.yml

device-cloud-for-maestro 0.0.7

---

steps/sonarqube-scanner/1.0.11/step.yml

sonarqube-scanner 1.0.11

---

steps/firebase-app-distribution/0.12.0/step.yml

Firebase app distribution 0.12.0

---

steps/firebase-app-distribution/0.12.1/step.yml

firebase-app-distribution 0.12.1

---

steps/zscan-upload-plugin/1.0.3/step.yml
steps/zscan-upload-plugin/step-info.yml

zscan-upload-plugin 1.0.3

---

steps/zscan-upload-plugin/assets/icon.svg

Add Zimperium logo icon

---

steps/maestro-ios-test-run/0.0.2/step.yml

maestro-ios-test-run 0.0.2

---

steps/genymotion-cloud-saas-start/0.1.7/step.yml

genymotion-cloud-saas-start 0.1.7

---

steps/appgallery-deploy/1.5.8/step.yml

appgallery-deploy 1.5.8
