bitrise-io/bitrise-steplib

steps/carthage/1.0.4/step.yml

Make `platform` an input param, letting `carthage` to build for Mac as well.

carthage 1.0.4

---

steps/xcode-archive-mac/1.0.0/step.yml

generates/handles export options plist for Xcode 7.0 or above projects

xcode-archive-mac 1.0.0

---

steps/xcode-archive-mac/1.1.0/step.yml

Proper handling of `export` methods as input.  Add support for `pkg` export.

xcode-archive-mac 1.1.0

---

steps/xcode-archive-mac/1.1.1/step.yml

update descriptions to make it more clear how to use `export_options_path` and `export_method`

Xcode archive mac

---

steps/gradle-coveralls/1.0.0/step.yml

This simple step sends code coverage to www.coveralls.io. Uses ./gradlew for task execution.
> I can't add labels, but please don't merge this one, as it's blocked by this PR. My pull request, which adds Bitrise support, was accepted, but the new version of library isn't released yet.
Contains fixes from https://github.com/bitrise-io/bitrise-steplib/pull/262

gradle-coveralls 1.0.0

---

steps/gradle-coveralls/1.0.1/step.yml

Added `coveralls_repo_token` to the `inputs`. 
In `1.0.0` version, COVERALLS_REPO_TOKEN should be exported manually. Now it will be exported by the step automatically.

gradle-coveralls 1.0.1

---

steps/applivery-ios/0.1.1/step.yml

Improved version including Bitrise team [feedback](https://github.com/bitrise-io/bitrise-steplib/pull/297)
- Dropped dependencies
- Removed all `is_dont_change_value: false`
- Removed all `is_expand: true`
- Removed all `is_required: true`
- Shortened Step ID: `applivery-ios`
- Three component SemVer version
- Dropped the additional indentation on description
- `run_if: .IsCI`
- Not print/log API TOKEN
- Improved Secret and Env Vars
- Added support for string Booleans
- Removed `os: ios` default value and moved hardcoded to` step.sh`

applivery-ios 0.1.1

---

steps/applivery-android/0.1.0/step.yml

Hi again guys
Now I'm performing a pull request for the Android step, forked from the iOS one. This one has been successfully tested in Bitrise.io with a Google sample App.
Please, note that I'm a little bit worried cause every time I follow the `bitrise share` steps, I found that in the process something extrange happends with the double quotes around `apk_path: $BITRISE_APK_PATH` that should look like  `apk_path: "$BITRISE_APK_PATH"`
As you can see, they are correctly written in the [original](https://github.com/applivery/steps-applivery-android-deploy/blob/master/step.yml#L27) but not [here](https://github.com/bitrise-io/bitrise-steplib/compare/master...applivery:applivery-android?expand=1#diff-c6b9d157f22170d28cc809250b822452R31)... is it normal?
Thanks and regards

applivery-android 0.1.0

---

steps/cordova-android/0.9.0/step.yml

This step adds support for cordova-based Android. It requires [vgaidarji/docker-android-cordova](https://hub.docker.com/r/vgaidarji/docker-android-cordova/) docker image.

cordova-android 0.9.0

---

steps/cordova-android/0.9.2/step.yml

Corrected `platform_name` parameter name. 
Previously `step.yml` had parameter `platform`, but  `step.sh` was expecting `platform_name` parameter.

cordova-android 0.9.2

---

steps/set-android-application-attributes/0.9.0/step.yml

This step allows to change the initial attributes of the `<application>` tag specified in AndroidManifest.xml

set-android-application-attributes 0.9.0

---

steps/post-jira-comment-with-build-details/0.1.4/step.yml

- Rewritten in PHP. Bash part similar from https://github.com/bitrise-io/steps-slack-message)
- Add dependencies for PHP both with homebrew and apt-get (but did not check with Android project. I will fo it later)
- Add output variable (JIRA_ISSUE_KEY)
- Rewrite "run_if" condition
- Add tags

post-jira-comment-with-build-details 0.1.4

---

steps/set-xcode-plist-value/1.0.0/step.yml

I have added a new step which allows users to modify a key value in a plist, this is great if you wish to inject build specific variables into a property list.

set-xcode-plist-value 1.0.0

---

steps/version-pre-release-info/1.0.0/step.yml

Hi,
I've added the following step that generates version containing pre-release information (`v1.0.0-alpha.1`, `2.4.1.beta+2`, `v2.0-rc.3`) based on git tags. Define which pre-release identifier and initial number do you want to use for your workflow (`alpha`, `beta`, `rc`) and which format do you prefer. The provided app version will be extended with this information.

version-pre-release-info 1.0.0

---

steps/aws-device-farm-file-deploy/0.0.1/step.yml

- Note: This test requires additional configuration to pass:
1. `AWS_ACCESS_KEY` and `AWS_SECRET_KEY` must be set in `.bitrise.secrets.yml`
1. An Amazon device farm project must be set up in the target region, and its ARN must be specified in the `device_farm_project` input (see `step.yml` for more info on obtaining the ARN)
1. `upload_file_path` input must be set to the path of any local file
- I was unable to locate the `stepman` tool on my `PATH` even though `bitrise` is installed and works OK.

aws-device-farm-file-deploy 0.0.1

---

steps/applivery-ios/0.2.1/step.yml

Added support for `autoremove` param that automatically removes the oldest build before uploading a new one to prevent reaching account limits. By default it's set to `true` for any automatic deployment system.

applivery-ios 0.2.1

---

steps/applivery-android/0.2.1/step.yml

Added support for `autoremove` param that automatically removes the oldest build before uploading a new one to prevent reaching account limits. By default it's set to `true` for any automatic deployment system.

applivery-android 0.2.1

---

steps/generate-text-file/0.0.2/step.yml

This step allows users to create a generic text file they can use further down in the process. This is useful for e.g. creating a What's New message for the Play Store deploy step based on the Git commit messages.
Factored in changes requested in PR #870 and released new version.

Generate text file 0.0.2

---

steps/wait-for-android-emulator/0.9.0/step.yml

wait-for-android-emulator 0.9.0

---

steps/android-sdk-update/1.0.2/step.yml

Update the step to use the `sdkmanager` tools instead the deprecated `android` tools.

android-sdk-update 1.0.2

---

steps/wait-for-android-emulator/1.0.0/step.yml

wait-for-android-emulator 1.0.0

---

steps/wait-for-android-emulator/1.0.1/step.yml

wait-for-android-emulator 1.0.1

---

README.md

http://devcenter.bitrise.io/docs/step-dev pointing to 404 error page replaced with http://devcenter.bitrise.io/bitrise-cli/create-your-own-step

Create your own step link fixed

---

steps/wait-for-android-emulator/1.0.2/step.yml

wait-for-android-emulator 1.0.2

---

steps/aws-device-farm-runner/0.0.5/step.yml

***
* Incorporate patch from andreschab90: [add opportunity for metered/unmetered BillingMethod](https://github.com/peartherapeutics/bitrise-aws-device-farm-runner/pull/26)
* [Make boolean options into drop-downs in step editor](https://github.com/peartherapeutics/bitrise-aws-device-farm-runner/pull/29)
* [Add error message with hint about test_package_name](https://github.com/peartherapeutics/bitrise-aws-device-farm-runner/pull/30)
* [point users to wiki for setup instructions](https://github.com/peartherapeutics/bitrise-aws-device-farm-runner/pull/31)
* [fix up formatting of input descriptions](https://github.com/peartherapeutics/bitrise-aws-device-farm-runner/pull/32)
* normalize type tags

aws-device-farm-runner 0.0.5

---

steps/diawi-upload/0.0.2/step.yml

Hi,
This is a tiny step which just formalises loading the diawi npm module, and then using it to upload an ipa/apk/zip to Diawi for distribution (https://www.diawi.com).
This is the first time I've done this, so let me know if you need me to change anything :)

diawi-upload 0.0.2

---

steps/wait-for-android-emulator/1.0.3/step.yml

wait-for-android-emulator 1.0.3

---

steps/wait-for-android-emulator/1.0.4/step.yml

wait-for-android-emulator 1.0.4

---

steps/set-android-manifest-values/1.0.1/step.yml

@viktorbenei, here's a cleaned up version of the Android manifest setter step. Currently supports package id, label, versionCode, and versionName. Uses xmlstarlet for document traversal, instead string replacement, so users don't need to have specific strings in place in their source code.
Can easily be updated in the future to support more values.
(My last PR accidentally had some leftover test code in the step.sh. Now removed.)

set-android-manifest-values 1.0.1

---

steps/bitrise-step-stamp-appicon-with-version-number/1.0.0/step.yml

Hi, I made a step that will use imagemagick to stamp a "version(build)" banner to iOS app icon.
- [x ] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [x ] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [x ] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [ x] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

bitrise-step-stamp-appicon-with-version-number 1.0.0

---

steps/deploy-to-itunesconnect-shenzhen/step-info.yml

For testing. If it works we should keep it enabled, otherwise we'll just disable it again with the same removal date IMO

Delete step-info.yml - re-enable Shenzhen step

---

steps/push-notification-with-parse/step-info.yml

because the Push Notifications are no longer supported by Parse server.

refactor(deprecation): push-notification-with-parse step deprecated 

---

steps/install-bundler/1.0.0/step.yml

This step basically checks if the current machine bundler gem is able to operate in the project. If the check fails, it looks for a Gemfile.lock to extract the Bundled version, and install that version in the machine.
This was created to [fix a problem](https://discuss.bitrise.io/t/machine-unable-to-use-update-bundler-2-0/7862/5?u=fwigor) when running projects bundled with bundle version 2.x on macOS machines.

Publish a step that allows the user to re-install the bundler gem based on a Gemfile.lock

---

steps/cocoapod-key/1.0.0/step.yml

The goal of this step is to allow the CI to inject keys into an iOS project using [cocoapods-keys plugin](https://www.github.com/orta/cocoapods-keys). So, the value is securely stored into source code.

Step to install keys through cocoapods-keys plugin

---

steps/cocoapod-key/1.0.1/step.yml

This PR creates a new version of the cocoapod-key step [fixing a typo problem](https://github.com/bitrise-io/bitrise-steplib/pull/1904#discussion_r258079160).

Fix typo on cocoapods-keys 1.0.0

---

steps/magicpod-ui-test/0.1.1/step.yml

Sorry for the frequency. Since there are several problems in the first version and we have changed our service's spec a little, we'd like to update the step definition.

magicpod-ui-test 0.1.1

---

steps/magicpod-ui-test/0.26.0/step.yml

The version of our step jumps from the previous one(0.1.1) because we'd like to follow the version of our [product](https://github.com/Magic-Pod/japanese-issue-and-doc/blob/master/CHANGELOG.md)(Sorry, it's written in Japansese). Is this okay for Bitrise?

magicpod-ui-test 0.26.0

---

steps/browserstack-app-live-upload/1.0.0/step.yml

It should be noted that this step is different from the [browserstack-upload](https://github.com/bitrise-io/bitrise-steplib/tree/master/steps/browserstack-upload) step.  **browserstack-upload** uses the _app-automate_ Browserstack endpoint.
This step, **browserstack-app-live-upload**, uses Browserstack's _app-live_ endpoint.

browserstack-app-live-upload 1.0.0

---

steps/close-jira-tasks/1.0.0/step.yml

Hi, this is step used in our organization to close some tasks in Jira project. It may be considered a bit too custom, but works well for us.
In order to run tests there are some preparations need.
- the `JIRA_TOKEN` variable must be set and correct
- `./_tmp` directory must be changed to a git repository with git log containing given [smart commit](https://confluence.atlassian.com/fisheye/using-smart-commits-960155400.html), e.g. with line `GAS-123`.
- `jira_url` must be changed to existing Jira account with existing `jira_project_name` project
I don't know how to make this tests reproducible and idempotent unfortunately.

close-jira-tasks 1.0.0

---

steps/cocoapod-key/1.0.2/step.yml

This PR aims to fix an [issue reported](https://github.com/FutureWorkshops/bitrise-step-cocoapod-key/issues/3), giving more flexibility to the step.

cocoapod-key 1.0.2

---

steps/check-certificate/1.0.0/step.yml

This step allows the check of a TLS certificate against a server. This is useful to ensure that a SSL pining on an app will work as expected.

check-certificate 1.0.0

---

steps/appcenter-app-release/1.0.4/step.yml
steps/appcenter-app-release/1.0.5/step.yml

This is the functionality of v1.0.4 that addresses one of the comments with the PR for the 1.0.4 release.  
The step update workflow seems sub-optimal: I can't make a change to the 1.0.4 since it is already tagged in the source repo, so I have to make a new tag (in the source repo) & new PR (in bitrise-steplib).  I also couldn't find the docs for updating a step.  Fortunately, the commands were still in my bash history.
This step will be going away since bitrise is [coming out with their own version](https://github.com/fileformat/bitrise-step-appcenter-app-release/issues/21), so don't think it is worth breaking backwards compatibility on this step, so I have not addressed the pipe vs comma comment.
I also did not address the use of env vars: the script does not use them directly, only in …

Appcenter app release 1.0.5

---

steps/create-apple-documentation/1.0.0/step.yml

This is a re-creation of the PR #2277 with a new step ID, and fixes for the points raised by @lpusok review
This is a step that allows the Bitrise CI to run a [Jazzy](https://github.com/realm/jazzy) command to create and export formatted Apple documentation. This is useful for Framework developers that want to create a doc file to publish.

Create Apple's Documentation v1.0.0

---

steps/msbuild-sonarscanner-begin/0.9.1/step.yml

This step allows running SonarScanner for MSBuild against Xamarin projects.
Because of the specifics of the CLI, there are actually two Bitrsie steps developed:
- to run `begin` command
- to run `end` command
Having two Bitrise steps allows using other Bitrise steps in between to run tests, compile, archive, etc. This is the main difference from the already existing Bitrise step developed by **tbrushwyler**: [SonarQube MSBuild Scanner](https://github.com/tbrushwyler/bitrise-step-sonarqube-msbuild-scanner)
- [ x] __I will not move an already shared step version's tag to another commit__
- [x ] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [ x] I have a test …

msbuild-sonarscanner-begin 0.9.1

---

steps/msbuild-sonarscanner-begin/0.9.2/step.yml

Now it's possible to provide any additional Sonar Scanner properties in a separate field.
- [x ] __I will not move an already shared step version's tag to another commit__
- [ x] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [ x] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [ x] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [ x] I read and accept the [Abandoned Step …

msbuild-sonarscanner-begin 0.9.2

---

steps/loco/0.1.2/step.yml

- Fixed an issue where the exported translations are not placed in the chosen directory (they were being put in a subdirectory with the project's name)

loco 0.1.2

---

steps/bitrise-step-xctest-cobertura-xml/1.0.0/step.yml

Hi, here is a new small step to generate Cobertura formatted XML-file from xcresult bundle produced by Xcode 11. The file can be then uploaded for example to SonarQube. 

bitrise-step-xctest-cobertura-xml 1.0.0

---

steps/get-pubspec-version-and-build-number/1.0.3/step.yml

Not depending on any package. Using pure and simple `awk` command to get the version on both OS X and Ubuntu. (#2361)

Get pubspec version and build number 1.0.3

---

steps/diawi-upload/0.0.7/step.yml

- [ ? ] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
* Step is a wrapper around bitrise node library - it can't really be tested without a valid upload key and a test .ipa file. There is a test file in the step's repo, but the upload key requires a Diawi account. It's an open issue for the test to simply check the format of the command run without actually running it.

diawi-upload 0.0.7

---

steps/bitrise-step-stamp-appicon-with-version-number/1.2.0/step.yml

Updated the step dependencies to include Ghostscript. Probably the dependency was introduced in newer version of imagemagic or catalina, not sure.
Tried to fix step id fail in #2423

bitrise-step-stamp-appicon-with-version-number 1.2.0

---

steps/bitrise-step-xctest-cobertura-xml/1.1.0/step.yml

Ported the step to use go-lang instead of swift, due to some issues introduced by Xcode 11.4. The step was already using go to run the script, so seemed like a good solution.

bitrise-step-xctest-cobertura-xml 1.1.0

---

steps/swiftformat/0.1.0/step.yml
steps/swiftformat/step-info.yml

[SwiftFormat](https://github.com/nicklockwood/SwiftFormat)
[SwiftForrmat Step Repo](https://github.com/dmiluski/bitrise-step-swiftformat)
https://github.com/kimdv/bitrise-step-swiftlint
Given SwiftFormat is a solution primarily targeted for code formatting, it lacks the enforcement protection for a repo. Although git hooks can make for autoformatting to occur automatically, it also is not a requirement to perform changes/PRs.
This is an attempt to provide a format enforcement step to ensure the code adhears to a format definition.

Feature: Swiftformat Linting Verification Step

---

steps/bitbucket-server-post-build-status/0.0.10/step.yml

bitbucket-server-post-build-status 0.0.10

---

steps/bitbucket-server-post-build-status/0.0.11/step.yml

Fixes regression https://github.com/teameh/bitrise-step-bitbucket-server-post-build-status/issues/4

bitbucket-server-post-build-status 0.0.11

---

steps/version-extractor-android/0.3.0/step.yml

For steps added for the first time, the GitHub option **Allow edits from maintainers** is required (See the documentation on how to select it: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
**New Step**

version-extractor-android 0.3.0

---

steps/firebase-dsym-upload/1.1.0/step.yml

For steps added for the first time, the GitHub option **Allow edits from maintainers** is required (See the documentation on how to select it: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
Update to include new location of FirebaseCrashlytics as Fabric is being deprecated on November 15 2020.
Also added logging functionality for debug.

firebase-dsym-upload 1.1.0

---

steps/bitrise-step-xctest-cobertura-xml/1.2.0/step.yml

Fixed a small compatibility issue with older version of Go. Also added CI-test to step-repo.
https://github.com/ollitapa/bitrise-step-xctest-cobertura-xml/issues/2

bitrise-step-xctest-cobertura-xml 1.2.0

---

steps/get-flutter-version/step-info.yml

This PR adds the missing step-info.yml so that the pipeline for #2494 can pass.

Added maintainer for future get-flutter-version step

---

steps/git-tag-project-version-and-build-number/1.0.9/step.yml

git-tag-project-version-and-build-number 1.0.9

---

steps/git-tag-project-version-and-build-number/1.0.10/step.yml

git-tag-project-version-and-build-number 1.0.10

---

steps/xcode-build-version/step-info.yml

step-info.yml added for xcode-build-version step.

---

steps/ios-auto-provision-appstoreconnect/step-info.yml

step-info.yml added for ios-auto-provision-appstoreconnect step.

---

steps/xcuitestbrowserstack/1.0.11/step.yml

- [ yes] __I will not move an already shared step version's tag to another commit__
- [ yes] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [ yes] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [yes ] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step …

[URGENT]: xcuitestbrowserstack 1.0.11

---

steps/xcuitestbrowserstack/1.0.12/step.yml

- [yes] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [yes] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository) …

[URGENT] xcuitestbrowserstack 1.0.12. [API Update from borwsersack - and have to support two different responses ]

---

steps/create-apple-documentation/1.1.1/step.yml

Users have reported [issues with the latest version](https://github.com/FutureWorkshops/bitrise-step-create-apple-documentation/issues/4), that basically consists on problems for installing gems, and poor error messaging.
This new minor change tackles this issues.

create-apple-documentation 1.1.1

---

steps/find-jira-issue/0.0.1/step.yml
steps/find-jira-issue/step-info.yml

find-jira-issue 0.0.1

---

steps/lifx-notifier/1.1.1/step.yml

lifx-notifier 1.1.1

---

steps/cocoapod-key/1.1.0/step.yml

This PR aims to publish the version 1.1.0 of the "Install Cocoapod Keys" step.
As reported by an user of the step [on an issue](https://github.com/FutureWorkshops/bitrise-step-cocoapod-key/issues/5), there are user cases where this step would help with installing the necessary gems, but there would be no need for actually setting any actual key in the Keyring, since the keys can be read from pre-loaded keychain or from Bitrise's Secret/Environment.
A sample of the use of this new functionality is …

cocoapod-key 1.1.0

---

steps/add-trace-sdk/1.0.4/step.yml

https://github.com/bitrise-steplib/bitrise-step-add-trace-sdk/releases/1.0.4

add-trace-sdk 1.0.4

---

steps/codecov/step-info.yml

[PLAT-344]: Maintainer changed to verified

---

steps/firebase-dsym-upload/2.0.0/step.yml

This PR updates the step's default location of where `upload-symbols` is stored from its Fabric location to its FirebaseCrashlytics location. This change is required due to the fact that from November 15th 2020 Firebase will be deprecating Fabric in favour of FirebaseCrashlytics.

firebase-dsym-upload 2.0.0

---

steps/magic-pod/0.65.1/step.yml

magic-pod 0.65.1

---

steps/codecov/2.0.1/step.yml

codecov 2.0.1

---

steps/update-gitops-repository/0.1.2/step.yml
steps/update-gitops-repository/step-info.yml

https://github.com/bitrise-io/bitrise-step-update-gitops-repository/releases/0.1.2
**New Step**

update-gitops-repository 0.1.2

---

steps/add-trace-sdk/1.2.2/step.yml

https://github.com/bitrise-steplib/bitrise-step-add-trace-sdk/releases/1.2.2

Add trace sdk 1.2.2

---

steps/add-trace-sdk-android/0.0.2/step.yml

https://github.com/bitrise-steplib/bitrise-add-trace-sdk-android/releases/0.0.2
- [X ] __I will not move an already shared step version's tag to another commit__
- [X ] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [X ] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [X ] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this …

add-trace-sdk-android 0.0.2

---

steps/add-trace-sdk-android/0.0.3/step.yml

https://github.com/bitrise-steplib/bitrise-add-trace-sdk-android/releases/0.0.3
- [X ] __I will not move an already shared step version's tag to another commit__

add-trace-sdk-android 0.0.3

---

steps/add-trace-sdk-android/0.0.4/step.yml

https://github.com/bitrise-steplib/bitrise-add-trace-sdk-android/releases/0.0.4

add-trace-sdk-android 0.0.4

---

steps/add-trace-sdk-android/0.0.5/step.yml

https://github.com/bitrise-steplib/bitrise-add-trace-sdk-android/releases/0.0.5

add-trace-sdk-android 0.0.5

---

steps/jira-issue-update-build/0.1.3/step.yml
steps/jira-issue-update-build/0.1.4/step.yml
steps/jira-issue-update-build/step-info.yml

jira-issue-update-build 0.1.4

---

steps/add-trace-sdk/1.2.3/step.yml

https://github.com/bitrise-steplib/bitrise-step-add-trace-sdk/releases/1.2.3

add-trace-sdk 1.2.3

---

steps/smart-qa/0.0.1/step.yml
steps/smart-qa/step-info.yml

smart-qa 0.0.1

---

steps/appcenter-codepush-release-react-native/0.0.3/step.yml

appcenter-codepush-release-react-native 0.0.3

---

steps/comment-on-github-pull-request/0.10.0/step.yml

comment-on-github-pull-request 0.10.0

---

steps/add-trace-sdk-android/0.1.0/step.yml

https://github.com/bitrise-steplib/bitrise-add-trace-sdk-android/releases/0.1.0

add-trace-sdk-android 0.1.0

---

steps/cocoapod-key/2.0.0/step.yml

This version removes the key/value list from the step. These inputs were causing many issues and they were a bad usage of cocoapod-keys in a CI environment. This step will remain just as an installer of dependencies.

cocoapod-key 2.0.0

---

steps/s3-download/1.2.0/step.yml

If the user requested a file in a sub-directory of the bucket, the output of the step would point to the wrong folder locally. This fix ensures that the output environment variable actually points to the right file. The step had its tests updated to validate this case.

s3-download 1.2.0

---

steps/s3-download/1.2.1/step.yml

This step output was not properly resolving relative paths. So, placeholders like `~`, `.` and `..` were not expanded before setting the output. The non-expanded path could present issues on the latest steps if the steps do not have a proper input resolution. Version 1.2.1 sorts this issue by exporting the output environment variable with the full path. The tests in the `bitrise.yml` of the steps were updated to be able to check this case.

s3-download 1.2.1

---

steps/android-sdk-add-on-installer/0.0.1/step.yml
steps/android-sdk-add-on-installer/step-info.yml

The Android SDK can be extended with "extras", which are local maven repositories or fat AARs added to the `extra` folder of the `$ANDROID_HOME`. One example of this is the `intel` accelerators for emulators. Some library providers use this strategy to publish their code to clients, without having to publish the code into maven central.
This step downloads an XML file that conforms to the `http://schemas.android.com/sdk/android/addon` namespace, resolves its content, and installs in the Bitrise VM the archives indicated in the XML. The step also allows (optionally) to have the checksum of this content validated.
At the moment contributors do not have access to the CI workflow triggered by StepLib PRs. In case of a failed build, we ask for your patience. Maintainers of Bitrise Steplib will …

android-sdk-add-on-installer 0.0.1

---

steps/add-trace-sdk/1.2.4/step.yml

https://github.com/bitrise-steplib/bitrise-step-add-trace-sdk/releases/1.2.4

Add trace sdk 1.2.4

---

steps/cocoapods-dependency-check/0.0.2/step.yml

- [👍] __I will not move an already shared step version's tag to another commit__
- [👍 ] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [ 👍] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [ 👍] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step …

cocoapods-dependency-check 0.0.2

---

steps/autify-upload/0.0.1/step.yml
steps/autify-upload/assets/icon.svg
steps/autify-upload/step-info.yml

Autify upload 0.0.1

---

steps/lifx-notifier/1.2.1/step.yml

lifx-notifier 1.2.1

---

steps/s3-cache-push/0.1.0/step.yml
steps/s3-cache-push/step-info.yml

In my previous PR I got the feedback to remove the env variables like `cache_aws_access_key_id: $CACHE_AWS_ACCESS_KEY_ID`, but that's needed on my use case because I get some of the inputs from the Bitrise Secrets.
**New Step**

S3 cache push 0.1.0

---

steps/s3-cache-pull/0.1.0/step.yml
steps/s3-cache-pull/step-info.yml

In my previous PR I got the feedback to remove the env variables like `cache_aws_access_key_id: $CACHE_AWS_ACCESS_KEY_ID`, but that's needed on my use case because I get some of the inputs from the Bitrise Secrets.
**New Step**

S3 cache pull 0.1.0

---

steps/data-theorem-mobile-secure/1.0.0/step.yml

Same as https://github.com/bitrise-io/bitrise-steplib/pull/3134 but with the version updated to `1.0.0`

data-theorem-mobile-secure 1.0.0

---

steps/set-java-version/1.0.1/step.yml
steps/set-java-version/step-info.yml

https://github.com/bitrise-steplib/bitrise-step-set-java-version/releases/1.0.1
**New Step**

set-java-version 1.0.1

---

steps/oversecured/1.0.1/step.yml

Updating wrongly made changed in https://github.com/bitrise-io/bitrise-steplib/pull/3013
- [+] __I will not move an already shared step version's tag to another commit__
- [+] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [+] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [+] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have …

oversecured 1.0.1 (fix)

---

steps/git-tag-project-version-and-build-number/1.0.13/step.yml

git-tag-project-version-and-build-number 1.0.13

---

steps/nuget-restore/step-info.yml
steps/xamarin-android-test/step-info.yml
steps/xamarin-archive/step-info.yml
steps/xamarin-components-restore/step-info.yml
steps/xamarin-ios-test/step-info.yml

The following Xamarin steps are marked as deprecated:
- nuget-restore
- xamarin-android-test
- xamarin-ios-test
- xamarin-archive
- xamarin-components-restore

[MOB-222] Add deprecation note to Xamarin steps

---

steps/bitbucket-server-post-build-status/0.0.12/step.yml

Fix: Allow Multiple builds for one Hash Commit  - [KageRiyuu](https://github.com/KageRiyuu)

bitbucket-server-post-build-status 0.0.12

---

steps/xcode-result-bundle-to-checks/1.1.0/step.yml

Xcode result bundle to checks 1.1.0

---

README.md

I just fixed README's link for "create your own step"
Actual
- 404: https://devcenter.bitrise.io/bitrise-cli/create-your-own-step
Expected
- 202: https://devcenter.bitrise.io/en/steps-and-workflows/developing-your-own-bitrise-step.html#ot-fltr-modal

Fix create your own step link

---

steps/ios-auto-provision-appstoreconnect/step-info.yml
steps/ios-auto-provision/step-info.yml

- [-] __I will not move an already shared step version's tag to another commit__
- [-] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [-] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [-] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step …

Addded deprecation notice for auto provision Steps

---

steps/update-gitops-repository/1.0.0/step.yml

https://github.com/bitrise-io/bitrise-step-update-gitops-repository/releases/1.0.0

update-gitops-repository 1.0.0

---

steps/magic-pod/0.95.1/step.yml

magic-pod 0.95.1

---

steps/bitrise-step-nowsecure-auto-analysis/step-info.yml

- CLA signed ✅ 
- Icon is still missing but will be delivered later in a separate PR.

Make Nowsecure verified

---

steps/version-extractor-android/step-info.yml

Deprecate https://github.com/vladimirpetrovski/bitrise-step-version-extractor-android
Conversation: https://github.com/vladimirpetrovski/bitrise-step-version-extractor-android/issues/6

Add deprecation note to `version-extractor-android`

---

steps/aws-secrets-manager/2.1.0/step.yml

- Mark stored secret values as sensitive [[diff](https://github.com/MoneyLion/bitrise-step-aws-secrets-manager/compare/72b0bb599fa60abad1e423f92c6f4a969771106d..ca54ddf8f393d583dc302c25569073f6c08bd343)].

aws-secrets-manager 2.1.0

---

steps/bitrise-step-install-bundler/step-info.yml

The "Install specific bundler version" step is duplicated in the steplib:
- Correct version: [https://github.com/bitrise-io/bitrise-steplib/tree/master/steps/install-bundler](https://github.com/bitrise-io/bitrise-steplib/tree/master/steps/install-bundler)
- Duplication: [https://github.com/bitrise-io/bitrise-steplib/tree/master/steps/bitrise-step-install-bundler](https://github.com/bitrise-io/bitrise-steplib/tree/master/steps/bitrise-step-install-bundler)
The invalid version is being marked as …

Mark duplicated step as deprecated

---

steps/configcat-feature-flag-sync/0.0.3/step.yml

`What is Configcat` section was added to the description.

configcat-feature-flag-sync 0.0.3

---

steps/deploygate--upload-app-bitrise-step/1.1.2/step.yml

deploygate--upload-app-bitrise-step 1.1.2

---

steps/install-bundler/1.2.0/step.yml

1. Improved path resolution for Gemfile.lock file
2. Ensures bundle is properly installed before finishing the step

install-bundler 1.2.0

---

steps/xcode-start-simulator/0.1.0/step.yml

https://github.com/bitrise-steplib/bitrise-step-xcode-start-simulator/releases/0.1.0

xcode-start-simulator 0.1.0

---

steps/android-instrumented-test/0.1.0/step.yml
steps/android-instrumented-test/step-info.yml

https://github.com/bitrise-steplib/bitrise-step-android-instrumented-test/releases/0.1.0
Updates based on feedback from @lpusok and @koral-- in a previous PR (https://github.com/bitrise-io/bitrise-steplib/pull/3522)
Note: I'm still waiting on an updated icon from the design team, so I will add that here in a later PR.
**New Step**

android-instrumented-test 0.1.0

---

steps/deploygate--upload-app-bitrise-step/1.1.3/step.yml

This version includes only one bug fix.

deploygate--upload-app-bitrise-step 1.1.3

---

steps/add-trace-sdk/step-info.yml

This PR deprecates the bitrise-add-trace-sdk as it is not supported anymore

[STEP-1998] Deprecate bitrise-add-trace-sdk Step

---

steps/update-gitops-repository/1.1.0/step.yml

https://github.com/bitrise-io/bitrise-step-update-gitops-repository/releases/1.1.0

update-gitops-repository 1.1.0

---

steps/magic-pod/0.99.7/step.yml

magic-pod 0.99.7

---

steps/autify-upload/0.0.3/step.yml

I just fixed the docs style because the old style is serialized automatically

autify-upload 0.0.3

---

steps/set-pubspec-application-version/0.0.1/step.yml
steps/set-pubspec-application-version/step-info.yml

set-pubspec-application-version 0.0.1

---

steps/autify-test-run/1.0.0/step.yml
steps/autify-test-run/step-info.yml

autify-test-run 1.0.0

---

steps/autify-upload/1.0.0/step.yml

autify-upload 1.0.0

---

steps/save-cache/1.0.0/step.yml
steps/save-cache/step-info.yml

https://github.com/bitrise-steplib/bitrise-step-save-cache/releases/1.0.0
**New Step**

save-cache 1.0.0

---

steps/restore-cache/1.0.0/step.yml
steps/restore-cache/step-info.yml

https://github.com/bitrise-steplib/bitrise-step-restore-cache/releases/1.0.0
**New Step**

restore-cache 1.0.0

---

steps/rustup-install/0.1.1/step.yml

---
No yml changes from [0.1.0](https://github.com/bitrise-io/bitrise-steplib/pull/3572), just a fix for Xcode stacks.

rustup-install 0.1.1

---

steps/configcat-feature-flag-sync/0.0.4/step.yml

configcat-feature-flag-sync 0.0.4

---

steps/jira-issue-update-build/0.2.4/step.yml

Step contains following input changes:
* `bitrise_api_token` is made optional
These changes are not breaking (option above was required previously), so I kept the major version.

jira-issue-update-build 0.2.4

---

steps/data-theorem-mobile-secure/1.1.0/step.yml

This PR updates the Data Theorem Mobile Secure step to version 1.1.0, which updates the bash script to work better with Mac OS older versions of bash.

data-theorem-mobile-secure 1.1.0

---

steps/save-gradle-cache/1.0.0/step.yml
steps/save-gradle-cache/step-info.yml

https://github.com/bitrise-steplib/bitrise-step-save-gradle-cache/releases/1.0.0

save-gradle-cache 1.0.0

---

steps/save-npm-cache/1.0.0/step.yml
steps/save-npm-cache/step-info.yml

https://github.com/bitrise-steplib/bitrise-step-save-npm-cache/releases/1.0.0
**New Step**

save-npm-cache 1.0.0

---

steps/restore-npm-cache/1.0.0/step.yml
steps/restore-npm-cache/step-info.yml

https://github.com/bitrise-steplib/bitrise-step-restore-npm-cache/releases/1.0.0
**New Step**

restore-npm-cache 1.0.0

---

steps/save-spm-cache/1.0.0/step.yml
steps/save-spm-cache/step-info.yml

https://github.com/bitrise-steplib/bitrise-step-save-spm-cache/releases/1.0.0
**New Step**

save-spm-cache 1.0.0

---

steps/restore-spm-cache/1.0.0/step.yml
steps/restore-spm-cache/step-info.yml

https://github.com/bitrise-steplib/bitrise-step-restore-spm-cache/releases/1.0.0
**New Step**

restore-spm-cache 1.0.0

---

steps/save-cocoapods-cache/1.0.0/step.yml
steps/save-cocoapods-cache/step-info.yml

https://github.com/bitrise-steplib/bitrise-step-save-cocoapods-cache/releases/1.0.0
**New Step**

save-cocoapods-cache 1.0.0

---

steps/restore-cocoapods-cache/1.0.0/step.yml
steps/restore-cocoapods-cache/step-info.yml

https://github.com/bitrise-steplib/bitrise-step-restore-cocoapods-cache/releases/1.0.0
**New Step**

restore-cocoapods-cache 1.0.0

---

steps/appcenter-app-release/step-info.yml
steps/create-android-emulator/step-info.yml
steps/deploy-to-itunesconnect-shenzhen/step-info.yml
steps/firebase-testlab/step-info.yml
steps/ios-auto-provision-appstoreconnect/step-info.yml
steps/ios-auto-provision/step-info.yml
steps/nuget-restore/step-info.yml
steps/start-android-emulator/step-info.yml
steps/xamarin-android-test/step-info.yml
steps/xamarin-archive/step-info.yml
steps/xamarin-components-restore/step-info.yml
steps/xamarin-ios-test/step-info.yml
steps/xamarin-test-cloud-for-android/step-info.yml
steps/xamarin-test-cloud-for-calabash-android/step-info.yml
steps/xamarin-test-cloud-for-calabash-ios/step-info.yml
steps/xamarin-test-cloud-for-ios/step-info.yml
steps/xamarin-user-management/step-info.yml

The messages were updated to contain Markdown links. Where it was applicable, I created links for the referenced steps.

docs: Update deprecation notice messages

---

steps/save-carthage-cache/1.0.0/step.yml
steps/save-carthage-cache/step-info.yml

https://github.com/bitrise-steplib/bitrise-step-save-carthage-cache/releases/1.0.0
**New Step**

save-carthage-cache 1.0.0

---

steps/restore-dart-cache/1.0.0/step.yml
steps/restore-dart-cache/step-info.yml

https://github.com/bitrise-steplib/bitrise-step-restore-dart-cache/releases/1.0.0
**New Step**

restore-dart-cache 1.0.0

---

steps/restore-carthage-cache/1.0.0/step.yml
steps/restore-carthage-cache/step-info.yml

https://github.com/bitrise-steplib/bitrise-step-restore-carthage-cache/releases/1.0.0
**New Step**

restore-carthage-cache 1.0.0

---

steps/artifact-pull/step-info.yml

This PR deprecates the Artifact Pull Step in favour of the Pull Intermediate Files Step.

Deprecated Artifact Pull Step

---

steps/update-gitops-repository/1.1.2/step.yml

https://github.com/bitrise-io/bitrise-step-update-gitops-repository/releases/1.1.2

update-gitops-repository 1.1.2

---

steps/magic-pod/0.99.24/step.yml

Updated dependencies to resolve a known vulnerability.

magic-pod 0.99.24

---

steps/update-gitops-repository/1.1.3/step.yml

https://github.com/bitrise-io/bitrise-step-update-gitops-repository/releases/1.1.3

update-gitops-repository 1.1.3

---

steps/maestro-ios-test-run/0.0.1/step.yml
steps/maestro-ios-test-run/step-info.yml

maestro-ios-test-run 0.0.1

---

steps/bitrise-step-appdome-build-2secure-ios/1.0.2/step.yml
steps/bitrise-step-appdome-build-2secure-ios/step-info.yml

bitrise-step-appdome-build-2secure-ios 1.0.2

---

steps/appdome-build-2secure-android/step-info.yml
steps/appdome-build-2secure-ios/step-info.yml

Verify Appdome

---

steps/appdome-build-2secure-ios/1.0.6/step.yml

Update to existing step:
- added return values

appdome-build-2secure-ios 1.0.6

---

steps/activate-build-cache-for-tuist/1.0.0/step.yml
steps/activate-build-cache-for-tuist/step-info.yml

https://github.com/bitrise-steplib/bitrise-step-activate-tuist-cache/releases/1.0.0
**New Step**

activate-build-cache-for-tuist 1.0.0

---

steps/activate-build-cache-for-gradle/1.0.0/step.yml
steps/activate-build-cache-for-gradle/step-info.yml

https://github.com/bitrise-steplib/bitrise-step-activate-gradle-remote-cache/releases/1.0.0
**New Step**

activate-build-cache-for-gradle 1.0.0

---

steps/activate-build-cache-for-tuist/1.0.1/step.yml

https://github.com/bitrise-steplib/bitrise-step-activate-tuist-cache/releases/1.0.1

activate-build-cache-for-tuist 1.0.1

---

steps/bitrise-step-appdome-build-2secure-ios/step-info.yml

Deprecate Install: bitrise-step-appdome-build-2secure-ios

---

steps/appdome-build-2secure-android/1.0.12/step.yml

appdome-build-2secure-android 1.0.12

---

steps/appdome-build-2secure-ios/1.0.12/step.yml

appdome-build-2secure-ios 1.0.12

---

steps/activate-build-cache-for-tuist/1.0.2/step.yml

https://github.com/bitrise-steplib/bitrise-step-activate-tuist-cache/releases/1.0.2

activate-build-cache-for-tuist 1.0.2

---

steps/activate-build-cache-for-gradle/1.0.1/step.yml

https://github.com/bitrise-steplib/bitrise-step-activate-gradle-remote-cache/releases/1.0.1

activate-build-cache-for-gradle 1.0.1

---

steps/create-new-app-store-release/1.0.0/step.yml
steps/create-new-app-store-release/step-info.yml

https://github.com/bitrise-steplib/bitrise-step-create-new-app-store-release/releases/1.0.0
**New Step**

Create new app store release 1.0.0

---

steps/run-tests-using-marathon-cloud/0.1.2/step.yml
steps/run-tests-using-marathon-cloud/step-info.yml

run-tests-using-marathon-cloud 0.1.2

---

steps/data-theorem-mobile-secure/1.2.0/step.yml

This PR updates the Data Theorem Mobile Secure step to version 1.2.0, which adds an optional sourcemap parameter which can be used to submit mapping files for android builds.

data-theorem-mobile-secure 1.2.0

---

steps/activate-build-cache-for-tuist/1.0.4/step.yml

https://github.com/bitrise-steplib/bitrise-step-activate-tuist-cache/releases/1.0.4

activate-build-cache-for-tuist 1.0.4

---

steps/activate-build-cache-for-tuist/1.0.3/step.yml

https://github.com/bitrise-steplib/bitrise-step-activate-tuist-cache/releases/1.0.3

activate-build-cache-for-tuist 1.0.3

---

steps/activate-build-cache-for-tuist/1.0.5/step.yml

https://github.com/bitrise-steplib/bitrise-step-activate-tuist-cache/releases/1.0.5

activate-build-cache-for-tuist 1.0.5

---

steps/configcat-feature-flag-sync/0.0.6/step.yml

configcat-feature-flag-sync 0.0.6

---

steps/codecov/3.3.1/step.yml

codecov 3.3.1

---

steps/codecov/3.3.2/step.yml

codecov 3.3.2

---

steps/activate-build-cache-for-tuist/1.0.6/step.yml

https://github.com/bitrise-steplib/bitrise-step-activate-tuist-cache/releases/1.0.6
- [V] __I will not move an already shared step version's tag to another commit__
- [V I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [V] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [V] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this …

activate-build-cache-for-tuist 1.0.6

---

steps/activate-build-cache-for-tuist/1.0.7/step.yml

https://github.com/bitrise-steplib/bitrise-step-activate-tuist-cache/releases/1.0.7
- [V] __I will not move an already shared step version's tag to another commit__
- [V] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [V] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [V] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this …

activate-build-cache-for-tuist 1.0.7 (tuist. 3.28.0)

---

steps/configcat-feature-flag-sync/0.0.7/step.yml

configcat-feature-flag-sync 0.0.7

---

steps/activate-build-cache-for-tuist/step-info.yml

Deprecating the `Activate Build Cache for Tuist` step. For more details please see: https://bitrise.io/blog/post/tuist-bitrise-build-cache-update

Activate Build Cache for Tuist step deprecation

---

steps/xctest-html-report/step-info.yml

Deprecate legacy xctest-html-report step

---

steps/bitrise-step-activate-bazel-cache/1.0.0/step.yml
steps/bitrise-step-activate-bazel-cache/step-info.yml

https://github.com/bitrise-steplib/bitrise-step-activate-bazel-cache/releases/1.0.0
**New Step**

bitrise-step-activate-bazel-cache 1.0.0

---

steps/git-tag-project-version-and-build-number/1.0.14/step.yml

git-tag-project-version-and-build-number 1.0.14

---

steps/bitrise-step-restore-cache/2.0.0/step.yml
steps/bitrise-step-restore-cache/step-info.yml

https://github.com/bitrise-steplib/bitrise-step-restore-cache/releases/2.0.0
**New Step**

bitrise-step-restore-cache 2.0.0

---

steps/magic-pod/0.99.40/step.yml

Just updated the dependencies for vulnerabilities.

magic-pod 0.99.40 (#1)

---

steps/update-gitops-repository/1.1.6/step.yml

https://github.com/bitrise-io/bitrise-step-update-gitops-repository/releases/1.1.6

update-gitops-repository 1.1.6

---

steps/dsym-upload-to-crashlytics--no-cocoapods/0.0.1/step.yml
steps/dsym-upload-to-crashlytics--no-cocoapods/step-info.yml

dsym-upload-to-crashlytics-spm 0.0.1

---

steps/docker-build-push/1.0.0/step.yml
steps/docker-build-push/step-info.yml

https://github.com/bitrise-steplib/bitrise-step-docker-build-push/releases/1.0.0
**New Step**

feat: GCI-15 docker-build-push 1.0.0

---

steps/update-jira-release-status/0.0.1/step.yml
steps/update-jira-release-status/step-info.yml

update-jira-release-status 0.0.1

---

steps/instabug-ios-symbol-upload/1.0.4/step.yml
steps/instabug-ios-symbol-upload/step-info.yml

instabug-ios-symbol-upload 1.0.4

---

steps/instabug-android-mapping-file-upload/1.0.2/step.yml
steps/instabug-android-mapping-file-upload/step-info.yml

instabug-android-mapping-file-upload 1.0.2

---

steps/update-gitops-repository/1.1.8/step.yml

https://github.com/bitrise-io/bitrise-step-update-gitops-repository/releases/1.1.8

update-gitops-repository 1.1.8

---

steps/activate-build-cache-for-bazel/1.0.0/step.yml
steps/activate-build-cache-for-bazel/step-info.yml

https://github.com/bitrise-steplib/bitrise-step-activate-build-cache-for-bazel/releases/1.0.0
**New Step**

activate-build-cache-for-bazel 1.0.0

---

steps/datadog-mobile-app-run-tests/1.0.0/step.yml
steps/datadog-mobile-app-run-tests/step-info.yml

datadog-mobile-app-run-tests 1.0.0

---

steps/datadog-mobile-app-upload/1.0.0/step.yml
steps/datadog-mobile-app-upload/step-info.yml

datadog-mobile-app-upload 1.0.0

---

steps/update-gitops-repository/1.1.9/step.yml

https://github.com/bitrise-io/bitrise-step-update-gitops-repository/releases/1.1.9

update-gitops-repository 1.1.9

---

steps/datadog-mobile-app-upload/1.0.2/step.yml

datadog-mobile-app-upload 1.0.2

---

steps/genymotion-cloud-saas-start/0.1.6/step.yml

genymotion-cloud-saas-start 0.1.6

---

steps/appdome-build-2secure-ios/3.1.0/step.yml

appdome-build-2secure-ios 3.1.0

---

steps/appdome-build-2secure-ios/3.1.1/step.yml

appdome-build-2secure-ios 3.1.1

---

steps/update-gitops-repository/1.1.11/step.yml

https://github.com/bitrise-io/bitrise-step-update-gitops-repository/releases/1.1.11

update-gitops-repository 1.1.11

---

steps/update-gitops-repository/2.0.1/step.yml

https://github.com/bitrise-io/bitrise-step-update-gitops-repository/releases/2.0.1

update-gitops-repository 2.0.1

---

steps/restore-gradle-configuration-cache/1.0.0/step.yml
steps/restore-gradle-configuration-cache/step-info.yml

https://github.com/bitrise-steplib/bitrise-step-restore-gradle-configuration-cache/releases/1.0.0
**New Step**

restore-gradle-configuration-cache 1.0.0

---

steps/update-gitops-repository/2.0.4/step.yml

https://github.com/bitrise-io/bitrise-step-update-gitops-repository/releases/2.0.4

update-gitops-repository 2.0.4

---

steps/appdome-build-2secure-ios/3.2.0/step.yml

appdome-build-2secure-ios 3.2.0

---

steps/appdome-build-2secure-android/3.3.1/step.yml

appdome-build-2secure-android 3.3.1

---

steps/disable-iphonesimulator-connect-hardware-keyboard/0.1.0/step.yml
steps/disable-iphonesimulator-connect-hardware-keyboard/step-info.yml

https://github.com/bitrise-steplib/steps-disable-iphonesimulator-connect-hardware-keyboard/releases/0.1.0
**New Step**

disable-iphonesimulator-connect-hardware-keyboard 0.1.0

---

steps/set-pubspec-application-version/1.0.0/step.yml

The change is that it is supported only for dart version 3 and above. Before dart version 2 was supported. It is a major breaking change.

set-pubspec-application-version 1.0.0

---

steps/deploy-react-native-update-to-appzung-codepush/1.0.0/step.yml
steps/deploy-react-native-update-to-appzung-codepush/step-info.yml

deploy-react-native-update-to-appzung-codepush 1.0.0

---

steps/appdome-build-2secure-android/3.4.1/step.yml

appdome-build-2secure-android 3.4.1

---

steps/version-pre-release-info/step-info.yml

Usage wise `bitrise-version-pre-release-info` is more common, but both steps have users to this day.

version-pre-release-info: mark duplicate step as deprecated

---

steps/stamp-appicon-with-version-number/step-info.yml

Discussion: https://github.com/ollitapa/bitrise-step-stamp-appicon-with-version-number/issues/5

stamp-appicon-with-version-number: mark duplicate step as deprecated

---

steps/update-gitops-repository/2.0.5/step.yml

https://github.com/bitrise-io/bitrise-step-update-gitops-repository/releases/2.0.5

update-gitops-repository 2.0.5

---

steps/magic-pod/1.38.0/step.yml

magic-pod 1.38.0

---

steps/activate-build-cache-for-xcode/0.0.1/step.yml
steps/activate-build-cache-for-xcode/step-info.yml

https://github.com/bitrise-steplib/bitrise-step-activate-build-cache-for-xcode/releases/0.0.1
**New Step**

Activate build cache for xcode 0.0.1

---

steps/activate-build-cache-for-xcode/0.0.3/step.yml

https://github.com/bitrise-steplib/bitrise-step-activate-build-cache-for-xcode/releases/0.0.3

activate-build-cache-for-xcode 0.0.3
